<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROCEED</name>
   <tag></tag>
   <elementGuidId>49aa27a5-63f3-4974-a010-05e7f60593fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_get_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_get_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>faafd5c3-4fe4-457e-9c46-cfbd4608824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17518aff-0a2f-4d4b-a0cd-76b85e14dc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-large bold w-100 h-fit</value>
      <webElementGuid>0aace066-b329-49a3-a448-8825f2bc3573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_get_address</value>
      <webElementGuid>6fd171c6-4408-4a83-8224-42df8d57d5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>237076db-65dc-41c9-b6f2-2828847f280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_get_address&quot;)</value>
      <webElementGuid>453e587d-a274-4c59-8a19-9cf8e16758e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>643ec4f9-c9fe-498b-aac4-9558ed63c88a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_get_address']</value>
      <webElementGuid>974f34cd-e494-4668-abb7-b90f000f8d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinGoogleMapModal']/div/div/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>f5b06478-8933-4cb4-aeba-653b0eb13940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 813'])[1]/following::button[1]</value>
      <webElementGuid>c2deaf71-22fc-4cb5-b156-c5275751ab30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 811'])[1]/following::button[1]</value>
      <webElementGuid>6f8329dd-f8cc-44e2-b038-0bbf1938e12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[2]/preceding::button[1]</value>
      <webElementGuid>11c5a530-edcb-4c00-8ecb-e63d85611fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>d1b18ab3-5a14-403b-9e54-091f9bd657cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_get_address' and (text() = 'PROCEED' or . = 'PROCEED')]</value>
      <webElementGuid>94ed3457-8be1-4dc4-bb9d-1683c5b61d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
