<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframepage-content-wrapper</name>
   <tag></tag>
   <elementGuidId>b5f3dfff-3655-4f87-b644-5ed053372b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>42bdc9dd-a9d5-4196-b756-a0a826bc1530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>97e91b67-90b7-4d88-b297-146e2a252670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX</value>
      <webElementGuid>92edc29d-aaa7-4a5f-8505-34d08d471d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>40dfa5e0-e5a7-4b3d-87cc-910798ff7739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>09b13f58-2130-4027-8be1-9bb223979b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>4228ce3d-2f99-4bdc-9b07-9f01a1bb700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cf5cd458-cb30-4d5c-a350-b0c29911fe43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX']</value>
      <webElementGuid>83257811-496e-4436-a448-c18a8892798b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
