<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfotctno</name>
   <tag></tag>
   <elementGuidId>deaa8d3b-9666-44e2-83f8-a93b8e1aa32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_tctno_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_tctno_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d59a41bf-8a66-4e54-b25f-63846b4cd50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a65866d8-1016-4146-928b-c370e7ebefa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>756aa4f3-829b-456e-941c-f42912492c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-class</name>
      <type>Main</type>
      <value>text_tctno</value>
      <webElementGuid>a9a7e655-6f01-40b5-90e6-8793156bf921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_tctno_1</value>
      <webElementGuid>55b7ec3f-53ce-46c2-9926-d1d0f4aa6761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[tctno]</value>
      <webElementGuid>d459f8a4-1622-4516-b682-e39bd9175e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{1,}</value>
      <webElementGuid>d6fb423c-475b-4d0b-95d3-75196cce8418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>ab9e76ea-639f-4b6b-a292-92ee44d3858c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_tctno_1&quot;)</value>
      <webElementGuid>db4c08f6-7650-4b54-aa22-ecbabed4fa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>4231a56b-ee84-4f66-b400-8d6f8438e1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_tctno_1']</value>
      <webElementGuid>15382a6e-d5d5-4d93-a24e-b5d4bfd05781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tct_container']/div/div/div/input</value>
      <webElementGuid>e4336f36-44ec-42f5-9815-0ac267754191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>a8ffdf1e-d4e6-40c4-8cde-221e1a18c349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_tctno_1' and @name = 'txt_lcinfo[tctno]']</value>
      <webElementGuid>b39d26a1-5d85-4a9a-a427-6a52dbe586c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
