<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Block No_txt_lcinfohblasubf_ha</name>
   <tag></tag>
   <elementGuidId>627e5b88-4146-454e-84bf-73fdc5ea803f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_blockno_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_blockno_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>454b49e0-0ee9-48c3-8444-d3acf9787e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96d51f80-56b7-4de6-841d-c9b7d5a07048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>a3121621-38c0-4fda-8715-1367a7ec679f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_blockno_ha</value>
      <webElementGuid>1cf2c9b0-381c-4b04-84c8-ea657b79d674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[hblasubf_ha]</value>
      <webElementGuid>5abce518-260b-400f-835f-db13d5a7b9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>dc8303b2-b4bc-4d53-84b6-8f626dd002b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>addressfields</value>
      <webElementGuid>701b95ba-a6b0-4fca-8c99-be3edcd1a72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_blockno_ha&quot;)</value>
      <webElementGuid>f8665b2b-5df0-48b8-9f83-73239f6013f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>e59166b9-8310-4117-89e2-047914f20472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_blockno_ha']</value>
      <webElementGuid>4ec9457b-49d5-4dd4-999f-0acdd0f93d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div[2]/div[2]/div/input</value>
      <webElementGuid>e1e725d3-305b-4f8d-ab53-6cf9df9469ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/div/input</value>
      <webElementGuid>10d24da2-fa5c-46fc-9f16-b0eed5668eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_blockno_ha' and @name = 'txt_lcinfo[hblasubf_ha]']</value>
      <webElementGuid>78161cbf-d625-4c5f-a4d2-3d757d94bade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
