<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_txt_lcinfozipc_lpe</name>
   <tag></tag>
   <elementGuidId>94acc3c8-ddad-4e94-9f24-db5838f7a6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_zipc_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_zipc_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3aa2d2-e402-44aa-a815-e6c0ecee692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6f8e00f-6fa3-4b6d-b8f2-8fa53c0a4913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>d45b2ff3-b637-455e-b8cc-7828eb9fd025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_zipc_lpe</value>
      <webElementGuid>b76605f9-3a2e-4cd7-9117-51005ec845b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[zipc_lpe]</value>
      <webElementGuid>56575e5f-672b-428e-9ba3-971d964769b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{4}</value>
      <webElementGuid>9128d2d4-f772-45ec-825b-1b1584f7db29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>27d60dbf-9dab-4e94-9c84-c6d1c59068ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXX</value>
      <webElementGuid>db449d4e-d57a-4dae-83be-9d74bec040b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ca1b2f43-6ad2-4754-a546-ae3991a40f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_zipc_lpe&quot;)</value>
      <webElementGuid>256835fb-545e-4353-a906-cba180fdb142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>5665bc09-3509-4f75-8d43-a7e1a2a6b7f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_zipc_lpe']</value>
      <webElementGuid>ffc335c7-74b9-4d1f-b021-20ca96c8b819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>8ba95079-b39c-40f1-8549-b888da1f8f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>9f131d7f-a5e6-4d05-a0e1-eed5822689ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_zipc_lpe' and @name = 'txt_lcinfo[zipc_lpe]' and @placeholder = 'XXXX']</value>
      <webElementGuid>cb1a29f2-b789-4792-8dd7-3ad813d7eb57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
