<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfohblasubf_ha</name>
   <tag></tag>
   <elementGuidId>a8a8d044-f01c-446b-91f4-47ef3ab88c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_lhne_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_lhne_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b16326f6-f3e6-40e2-aa10-d9e1bc3c1f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83558cc3-84fa-485f-923c-159da1ba9b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>481303d6-9116-4c57-b9d1-8ee3c2722c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_lhne_ha</value>
      <webElementGuid>abf117aa-b8a2-4ae1-a554-af898bdc10f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[hblasubf_ha]</value>
      <webElementGuid>cfd16892-f677-4929-bcf9-2e8dcf6bd4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>d1dc6cf4-d020-47d0-a020-0b590449059f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>addressfields</value>
      <webElementGuid>2acc20a2-34c7-4d54-bf7a-eaa4fd99fc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_lhne_ha&quot;)</value>
      <webElementGuid>34073b96-8d22-40c2-b239-1fece22d5e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>ff6ceceb-f5de-48d8-8997-c048408fbccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_lhne_ha']</value>
      <webElementGuid>75c74460-600f-49fb-946a-fa7781eb5ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div[2]/div/div/input</value>
      <webElementGuid>c807818a-5de5-48fb-ae45-649bb18ae245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>9fd45baa-fdc6-4612-9399-e62fdcc071c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_lhne_ha' and @name = 'txt_lcinfo[hblasubf_ha]']</value>
      <webElementGuid>82954cfb-bafd-43d3-8b56-68f91b74d089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
