<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project Cost_txt_lcinfoprojcos</name>
   <tag></tag>
   <elementGuidId>e543aac3-8402-4607-b8ce-362aed1793d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_projcos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_projcos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2f32925-480f-4865-8d97-27e4b9251d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b87b69f8-b2fe-4a7e-b7a0-648150023d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>8667f1ca-a9db-492a-8e6b-9e485d7c8c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_projcos</value>
      <webElementGuid>291b48ca-38ce-4ffd-8778-44bdd1b89ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[projcos]</value>
      <webElementGuid>c053d554-8334-4aa0-8b62-2efbb999abe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>57f667a4-72c3-4edd-98bd-5b2b91fc5028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>bcb57760-3e66-452a-a0f9-4c89bfef6d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_projcos&quot;)</value>
      <webElementGuid>fa37e5a0-19b1-488b-b441-fe3bc8bd9046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>5886ff13-2849-4a21-8c30-a6e5c4ab51b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_projcos']</value>
      <webElementGuid>ac68ddf0-dba5-46fd-808d-faa7ee1f90bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[3]/div/div/input</value>
      <webElementGuid>e616ae5c-b45c-42ac-a2c0-e78e5dc2a569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/div/input</value>
      <webElementGuid>dc34b256-8ac3-4583-8f18-f12ffa7b98fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_projcos' and @name = 'txt_lcinfo[projcos]']</value>
      <webElementGuid>1432c2cd-63cf-4cb9-80f4-1b6fa57843db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
