<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonopgm_fn</name>
   <tag></tag>
   <elementGuidId>2fb0ab33-2803-4ce4-9eae-3cf91fd5b4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nopgm_fn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nopgm_fn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72990d19-665a-4b39-b2c3-ebea9caa4527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27be6ed3-9ccd-4ddd-8beb-3e1845a0f5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>e53f1683-4065-48d6-a222-7c04e8bc4ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nopgm_fn</value>
      <webElementGuid>4b4b088b-51e0-460a-9a55-25d3aeaa5fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nopgm_fn]</value>
      <webElementGuid>43e170ce-a5f9-4a97-9074-624d11870568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\-\.][\u00F1\u00D1a-zA-Z\s\-\.']+</value>
      <webElementGuid>14c554c2-a0a7-468c-8164-a66546f23d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>personname</value>
      <webElementGuid>812084fb-a548-4582-a38a-3238017c4913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nopgm_fn&quot;)</value>
      <webElementGuid>b8766db5-128e-4f2d-bce4-acd1d7554672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>92486058-d468-49ea-a9a5-8e7e66a3e322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nopgm_fn']</value>
      <webElementGuid>1824bff9-a7da-485f-9e0a-f0380f88962f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div/div/input</value>
      <webElementGuid>75636e23-9059-48e1-a6fb-52db3b79a85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>9e75d9db-76b8-48df-a62f-74e9af45d4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nopgm_fn' and @name = 'txt_lcinfo[nopgm_fn]']</value>
      <webElementGuid>479e334e-eafe-4d30-ba40-0deeff7d3ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
