<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_txt_lcinfozipc_ha</name>
   <tag></tag>
   <elementGuidId>da2081be-d18a-4e6d-b7da-c8a2644e1d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_zipc_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_zipc_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cccfef7a-3de8-4697-bd37-130f3e2e9c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94a486e2-dacc-4cad-b169-8f3beb362d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>4d9a3de4-4add-4f75-ae60-2bb4a403df32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>aa7cc01b-0284-468b-b09a-8a5fcdf341cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[zipc_ha]</value>
      <webElementGuid>a2429ecd-a987-4436-93a3-af67ff305b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{4}</value>
      <webElementGuid>20f771fa-688e-4a2e-a90d-39c8000486b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>ae7eca3d-d24c-45f8-a220-87c80bb97ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXX</value>
      <webElementGuid>5df418de-7ef1-4a73-837f-3f36b38b3bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0d22c744-a7bf-45ac-b1fe-1cd682c8ed82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_zipc_ha&quot;)</value>
      <webElementGuid>72fca438-057e-4bca-9480-c641e779d74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>8b0bccfa-8906-4a2e-ab7d-88aa7b522778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_zipc_ha']</value>
      <webElementGuid>c98e3010-444c-40aa-88a2-3e046c3e9bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div[3]/div[2]/div/input</value>
      <webElementGuid>5ee08123-2adc-4364-9f3a-19af5cd800d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>59427a07-2683-42e7-9172-9f7b813a76e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_zipc_ha' and @name = 'txt_lcinfo[zipc_ha]' and @placeholder = 'XXXX']</value>
      <webElementGuid>b0b5af46-2506-4cad-b5ae-437de841e54a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
