<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please upload a file here_checkbox_at_f5debb</name>
   <tag></tag>
   <elementGuidId>10444e94-1742-4917-b58e-a8d3f657838b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox_attestation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox_attestation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8faeb3ac-6cbf-49e7-91e2-8b8af9cd8fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-auto</value>
      <webElementGuid>03b596f9-a794-4867-8d2a-0fac48a1eeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb038df3-b2b2-4ff5-bbfe-3755f43942c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox_attestation</value>
      <webElementGuid>86ebbc34-d91c-4f3f-b079-d571e30abfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5fac6784-a838-41c5-a582-9104f494f262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_attestation&quot;)</value>
      <webElementGuid>837c63e8-0a0f-4298-a0b6-f1eb77ff7f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>9137745e-39d3-4ecf-bb0c-ab7dcd7af1f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox_attestation']</value>
      <webElementGuid>cb7fda1d-36d0-495f-8bf4-11fce22d50f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='application_form']/div/div[4]/input</value>
      <webElementGuid>b98a540e-8a30-4213-9a81-790889c7bffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/input</value>
      <webElementGuid>4799e62c-d24b-4bf6-845d-39a1f1247aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox_attestation']</value>
      <webElementGuid>d53b4711-eb90-479e-b6d0-cdee9f454453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
