<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfophno_case</name>
   <tag></tag>
   <elementGuidId>5b75eab1-0ac9-467b-a9a7-9d8cbd08f162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_phno_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_phno_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb59a5aa-42be-42a8-b80c-f7697641da89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>050eeaa8-b387-412b-b76e-4fd6e9fdd3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>1266fa13-f9ea-442e-91a6-6f9c44f176bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_phno_case_2</value>
      <webElementGuid>88710c58-28ed-4d96-b658-d2b57846972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[phno_case]</value>
      <webElementGuid>2b0e9009-7318-45c3-811f-b66811aab992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>9XX-XXX-XXXX</value>
      <webElementGuid>f7fbcc60-c318-4d42-997f-2f7fed3ccb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[9][\d]{9}</value>
      <webElementGuid>0ce62d82-977f-432c-9970-ae49537d1f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>b0077735-86f1-43dd-b789-3a1d51065699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>79801438-9d4f-4d13-8632-b3f870113974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_phno_case_2&quot;)</value>
      <webElementGuid>82afddbb-e94c-4f0a-b7ed-6216776b05a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>dee4526b-ff4d-48ae-b03f-29b9a9c9f5ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_phno_case_2']</value>
      <webElementGuid>98f01f9c-38a2-4584-ba31-fc8ef693e820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>7ba7ac14-55ea-4bf7-aa76-4afcae3630d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>888745a0-fbab-4673-8df1-2a02dcd6a011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_phno_case_2' and @name = 'txt_lcinfo[phno_case]' and @placeholder = '9XX-XXX-XXXX']</value>
      <webElementGuid>c0f96465-cccb-46f3-990a-7f73e22f5066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
