<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfofau_sqm</name>
   <tag></tag>
   <elementGuidId>1ebf0a6d-8ff3-4d86-a605-d951921b5dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_fau_sqm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_fau_sqm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fd78794-c4e9-407c-890d-185f929a695d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d686e3dd-b90b-476f-a61b-190d5dbac1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>4c5b31cb-f6b9-44a1-b8ed-cd784f7d04b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_fau_sqm</value>
      <webElementGuid>cd3b0c61-095b-477b-ad74-ad7683e75402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[fau_sqm]</value>
      <webElementGuid>472a0185-b0fb-4cfb-a242-05bd3cf3f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>487d7bcc-a455-44b5-9972-47772eae9a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>348f25d5-809c-4727-b61b-d5d2b2fe6f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_fau_sqm&quot;)</value>
      <webElementGuid>077982e9-3a80-4d53-98a5-c0e759bdc310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>2379b689-6b1b-4955-ab14-395ed4d1b4e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_fau_sqm']</value>
      <webElementGuid>039131a3-903c-4d91-92a7-d429b6bf5208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[2]/div/div/input</value>
      <webElementGuid>fd01d8f4-16c5-4144-8dcc-e8a8964a5c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/input</value>
      <webElementGuid>3b07aab3-f5d9-4be3-a223-49d071f07e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_fau_sqm' and @name = 'txt_lcinfo[fau_sqm]']</value>
      <webElementGuid>cf0c5a79-47bb-40ca-aea3-2a6cd7f559b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
