<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross Floor Area of Building (sqm)_tx_aa6ffc</name>
   <tag></tag>
   <elementGuidId>fb7df1df-2be7-48fe-892f-d4a12f6c7a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_gfab_sqm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_gfab_sqm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>790cefb8-7afa-4e1c-a626-5557f9b135b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3f5175f-3746-4143-99bc-56a2febcb667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>1ae535f7-d05f-48da-9ab6-1ff0828e4102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_gfab_sqm</value>
      <webElementGuid>76837d98-44ea-45c4-bdbc-338fd6a4f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[gfab_sqm]</value>
      <webElementGuid>340b20ae-29a9-4a4b-bf35-883c903dfc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>79c384cb-ae72-4506-a69f-3b437d5419ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>d2b3efe1-9f3f-48ae-a0c8-0cc058b47a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_gfab_sqm&quot;)</value>
      <webElementGuid>49375bad-543a-40ef-8b0d-3742963ab226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>eaf48c5f-7061-47ff-b6db-e81ea8495487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_gfab_sqm']</value>
      <webElementGuid>7088e37b-21b8-4b39-9caa-8d7876a76d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>18d0853d-90e4-4359-a4a9-0bb13dff2a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>f6bbeb26-c18b-4e35-bc07-d3d76d053729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_gfab_sqm' and @name = 'txt_lcinfo[gfab_sqm]']</value>
      <webElementGuid>d6dc3d82-deb1-4510-92de-8639d5172758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
