<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_input_username</name>
   <tag></tag>
   <elementGuidId>4b0a8dad-9c32-4b03-afe2-6a94ac117e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>555c9b67-fa18-45c5-89c1-a651b737093c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d75db6d9-2065-4359-a56a-51c1f3eb4ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03ed3aad-2f59-4ffc-b0d1-bb4fd48affe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>4f4e1e08-69be-4248-bbf2-92167c42c638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>4df1bd19-489e-4608-8e6c-3ca89399d4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@email.com</value>
      <webElementGuid>b6eecf85-0c70-4ef2-ab79-e8b83ef14cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_username&quot;)</value>
      <webElementGuid>5185a94a-d1ab-4476-aef1-e92b4d1fafd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_username']</value>
      <webElementGuid>1765b829-3016-4a84-a04e-cd768389889d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_div']/div/input</value>
      <webElementGuid>ce7619e0-a379-4173-a85c-5c22e531c2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4fdc36e9-8a91-4ac2-bc86-41845252382f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_username' and @name = 'input_username' and @placeholder = 'example@email.com']</value>
      <webElementGuid>ab1d7d5f-1b53-4142-abbc-fe0058abc566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
