<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invalid field. Please enter proper te_3469a4</name>
   <tag></tag>
   <elementGuidId>d16e5d9f-d8af-460a-b685-8ebb2b3f4c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox_middle_name_nopgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox_middle_name_nopgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ec6a5c7-4938-44df-9170-a88a2571bf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a00ee8c-6ce7-498a-a688-f6c35b9c5efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input txt_lcinfo</value>
      <webElementGuid>41511f5a-81c9-4238-b045-cf0ef7cb40f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox_middle_name_nopgm</value>
      <webElementGuid>31de10aa-4ea3-49f7-a10c-f0bc45acbd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[no_middle_name]</value>
      <webElementGuid>2dca64ff-6780-477f-bec4-b6e161de6941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_middle_name_nopgm&quot;)</value>
      <webElementGuid>17dfc534-22aa-4495-acfb-077a4f056206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>4319dca8-b2fd-401b-bd1a-790a6a2db7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox_middle_name_nopgm']</value>
      <webElementGuid>2b39459d-1399-4398-9c2b-d30fc957b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>8a531801-0b04-46b1-9e4c-174ba3a11d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>edd023d8-e875-457e-8f80-89bd1c6ef228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox_middle_name_nopgm' and @name = 'txt_lcinfo[no_middle_name]']</value>
      <webElementGuid>92dd0cd1-d795-4782-b928-f3653ce941e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
