<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_INFORMATION_txt_lcinfoapp_position</name>
   <tag></tag>
   <elementGuidId>5e8fc7a2-2065-46ee-ae50-c0f36f41d378</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_applicant_owner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_applicant_owner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0665b5e9-f5eb-472a-9504-9e0b816cee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cfe2ff61-8fc4-4a79-8256-f297b86ac305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_applicant_owner</value>
      <webElementGuid>049428df-b60c-41e0-a264-11ef9d2607ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[app_position]</value>
      <webElementGuid>b0e62a7d-9c03-4705-9144-0fe3df60f925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_applicant_profile</value>
      <webElementGuid>3e77c3f0-09ad-4bdd-9826-8b9f286471dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio_applicant_profile</value>
      <webElementGuid>8cc9fdc4-c318-403c-880c-83e5062032b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7923aa3-4e1e-40e0-adcd-a42eb7cbe9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_applicant_owner&quot;)</value>
      <webElementGuid>1534aa37-a305-4982-9dc1-36720a1a90e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>984db902-5038-4e4d-a64a-cf51666f856b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_applicant_owner']</value>
      <webElementGuid>c3e7cc0e-1681-41cc-83a4-9d7d71225a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[2]/div/input</value>
      <webElementGuid>2ee13862-20af-4663-a49c-e26c0069a7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>a3756cc8-1ccc-49d5-82cd-d374124da487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_applicant_owner' and @name = 'txt_lcinfo[app_position]']</value>
      <webElementGuid>b9194345-7463-44d4-9a88-e5f72f61ca2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
