<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonopgm_ln</name>
   <tag></tag>
   <elementGuidId>ef2d677e-f406-46b9-b40c-d6006ee3c030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nopgm_ln</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nopgm_ln']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8739441a-bda1-4393-90cd-f036017fe4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53013aea-8a63-41cf-9b89-fe3b0d9c70a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>0f8bd4db-4258-43e6-8514-53dadacfd2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nopgm_ln</value>
      <webElementGuid>e538e576-1f7b-4582-bf03-b1129c104f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nopgm_ln]</value>
      <webElementGuid>cfcb869c-edca-41ba-b618-49eab8731a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\-\.][\u00F1\u00D1a-zA-Z\s\-\.']+</value>
      <webElementGuid>20d936cc-e35f-48a2-80d4-4206a1bc8ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>personname</value>
      <webElementGuid>4a58375a-05fc-424c-9430-868a79abad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nopgm_ln&quot;)</value>
      <webElementGuid>6988ecc1-f661-4ed0-bb84-587103ab9fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>49366b55-8324-4f63-8062-94dcee8586fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nopgm_ln']</value>
      <webElementGuid>046fae1d-20b6-4708-91fe-d8a15771f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[2]/div/input</value>
      <webElementGuid>7583e0a1-a596-4288-bf30-15c9a2b3227f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>35c10adb-bc4e-408f-99e3-9836dcd474eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nopgm_ln' and @name = 'txt_lcinfo[nopgm_ln]']</value>
      <webElementGuid>8bdb5a94-06c4-4adc-979a-c8277cd4d394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
