<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Construction_txt_lcinfonature_of__e085da</name>
   <tag></tag>
   <elementGuidId>1aa11f52-80d9-45c5-83ab-0481c10d7f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_nb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_nb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b5c0d1d-d698-4912-8dad-63974e7956e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a8d3639c-08da-49ca-a927-9447e3387e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_nb</value>
      <webElementGuid>338cf749-c9f3-45c4-98ec-74d4aabe0585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_lcinfo order-2</value>
      <webElementGuid>f97a51c1-93b5-4206-b789-16f7f498623c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nature_of_application]</value>
      <webElementGuid>ea912a29-050d-4c99-935b-8e378d31c67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_nature_of_application</value>
      <webElementGuid>60c54e70-3d35-46d5-be29-ce1654623ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b6451da5-e6b2-4587-93fa-c8158c256bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_nb&quot;)</value>
      <webElementGuid>05fa2c8d-e217-488d-afb8-5e491637ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>aec15cfc-5314-4981-85cd-3c3461ad8fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_nb']</value>
      <webElementGuid>2cf78382-b4ac-4a7c-8838-094b21c98d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nature_of_application_wrapper']/div[2]/div[2]/input</value>
      <webElementGuid>0f36a9ec-00b7-4720-9398-177fd87b58a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d9cd2359-8119-49b2-b303-22765b462f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_nb' and @name = 'txt_lcinfo[nature_of_application]']</value>
      <webElementGuid>a4527093-b868-4f82-a041-6277848e59bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
