<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfoemail_case</name>
   <tag></tag>
   <elementGuidId>1799e3af-ed9a-4fe3-a1d5-b91b0f312998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_email_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_email_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ed44752-38bb-4012-ab8f-58d274726f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8301a4e-f2eb-4594-879e-3a48121c396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>b5c561f8-0a25-41e7-83eb-13c9fc09dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_email_case_2</value>
      <webElementGuid>b80f6598-6fee-4047-a54e-93ac7df5ccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[email_case]</value>
      <webElementGuid>7f4097bf-0a49-4b86-a597-7caac598fb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9\-\._%+]+@([a-zA-Z0-9\-]{2,}\.)+[a-zA-Z0-9\-]{2,4}</value>
      <webElementGuid>dcac4e5e-b1eb-4ff9-90f5-c24f18359f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7b6c9492-9cab-4451-98f2-737ef63cf464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_email_case_2&quot;)</value>
      <webElementGuid>270cec36-38f4-49fe-b30f-0d75620101b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>d3ad09d8-5995-4507-a2b9-60afb4d898df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_email_case_2']</value>
      <webElementGuid>c9a73b19-067b-494f-a822-3b9184954d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>a6836984-fc63-45a9-bf29-ee1df7adfa6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>ba9fcd76-1978-4241-954d-bed1ae85cc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_email_case_2' and @name = 'txt_lcinfo[email_case]']</value>
      <webElementGuid>b8b7484d-288a-41fb-8280-6c9cb94c4f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
