<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select City -City of CaloocanCity _8a6f4b</name>
   <tag></tag>
   <elementGuidId>c27cd845-f9b1-446b-a782-8337c74035e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_city_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_city_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b66fb365-aabf-48e6-a4f9-210f53e3bc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[city]</value>
      <webElementGuid>4fc8bc25-5ab9-4c52-8cac-c8678d58d2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>08d26544-f7d7-423e-bcac-836349a5ff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control custom-select psgc_fields</value>
      <webElementGuid>707191ad-0a7a-43ad-84d3-99f320011f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>26528684-0311-4122-ac83-8c0e7359fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brgyid</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>1e45288e-a98e-40e9-bb9c-5acddc2994f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_munci_change(this)</value>
      <webElementGuid>74bceac0-8f4c-4fff-b9ac-54510d94bc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select City -City of CaloocanCity of Las PiñasCity of MakatiCity of MalabonCity of MandaluyongCity of ManilaCity of MarikinaCity of MuntinlupaCity of NavotasCity of ParañaquePasay CityCity of PasigQuezon CityCity of San JuanCity of TaguigCity of ValenzuelaPateros</value>
      <webElementGuid>7461f302-411a-4050-a00f-d640c3d0239a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_city_ha&quot;)</value>
      <webElementGuid>f9899958-b8e0-410f-aad8-c90236a9a3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>7ea32343-c03a-4a69-9731-60b99ba7740d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_city_ha']</value>
      <webElementGuid>07c45657-8d3a-4321-9e76-ed25fb9017de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[3]/div/select</value>
      <webElementGuid>3723a65b-4a2a-47db-9c77-e47ca9007b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[27]/following::select[1]</value>
      <webElementGuid>7fc27654-0b41-4fad-b791-8b6de049cbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a City.'])[1]/preceding::select[1]</value>
      <webElementGuid>6e8b23e4-ec7f-4d8e-b980-4139fce4a387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>e1b755c9-8aa0-4b26-9ce2-37eae5cec9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[city]' and @id = 'select_city_ha' and (text() = '- Select City -City of CaloocanCity of Las PiñasCity of MakatiCity of MalabonCity of MandaluyongCity of ManilaCity of MarikinaCity of MuntinlupaCity of NavotasCity of ParañaquePasay CityCity of PasigQuezon CityCity of San JuanCity of TaguigCity of ValenzuelaPateros' or . = '- Select City -City of CaloocanCity of Las PiñasCity of MakatiCity of MalabonCity of MandaluyongCity of ManilaCity of MarikinaCity of MuntinlupaCity of NavotasCity of ParañaquePasay CityCity of PasigQuezon CityCity of San JuanCity of TaguigCity of ValenzuelaPateros')]</value>
      <webElementGuid>9e1aeb75-02ce-4a2e-a673-82239a7f9f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
