<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Select Barangay Here-              _4b8666</name>
   <tag></tag>
   <elementGuidId>c2bdf9fc-121d-4965-b7a3-48cb5cc7d00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_barangay_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_barangay_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9810b37-f46e-4f6b-8e6f-6ea65d77b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bgy_sel custom-select psgc_fields</value>
      <webElementGuid>a26a2653-2671-4751-acbf-5bf98febf4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_barangay_lpe</value>
      <webElementGuid>510da623-d953-4dcf-89f9-2afd87603939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[barangay_lpe]</value>
      <webElementGuid>85fa0db8-1431-4281-91ab-ffd40a99e8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_lpe</value>
      <webElementGuid>f46738e6-a0f6-4ba9-9a48-9be1649156eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_brgy_change(this)</value>
      <webElementGuid>d5dc1457-f35f-41ab-8883-38029aade946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    -Select Barangay Here-
                    Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBuayang BatoBurolDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J.RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-AsaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-Wack Greenhills                </value>
      <webElementGuid>ee703e6b-ddb0-4f5a-b6a7-a35e2d4d5813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_barangay_lpe&quot;)</value>
      <webElementGuid>ca158f77-0d15-47f2-b37e-289e2cfba475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>19cfd3f6-0c04-4438-a016-b0b6bd17bd5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_barangay_lpe']</value>
      <webElementGuid>6f8fa007-8f66-421e-b6f8-8ed96b0311b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div/div[4]/select</value>
      <webElementGuid>a3443b1a-3785-4f1b-ab3e-6e538b2a1e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[35]/following::select[1]</value>
      <webElementGuid>1358ee53-9154-450c-9970-a21dcb118238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid field. Please select a barangay here.'])[1]/preceding::select[1]</value>
      <webElementGuid>5e1a7e21-006d-4c5c-87b6-90e78efbf525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>f18da1dd-a082-45cc-97ce-3816a432ed77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'select_barangay_lpe' and @name = 'txt_lcinfo[barangay_lpe]' and (text() = '
                    -Select Barangay Here-
                    Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBuayang BatoBurolDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J.RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-AsaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-Wack Greenhills                ' or . = '
                    -Select Barangay Here-
                    Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBuayang BatoBurolDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J.RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-AsaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-Wack Greenhills                ')]</value>
      <webElementGuid>59451f73-191a-4065-86fa-5c80957316d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
