<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Barangay -Addition HillsBag_512eb9</name>
   <tag></tag>
   <elementGuidId>cf33b57d-fd2d-4c42-9593-9471f74e990f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_barangay_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_barangay_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95ef8c7a-6455-4666-9cb6-5ddfdbb99150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[barangay]</value>
      <webElementGuid>44735028-167b-47e8-b629-1bd5da1a70db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>e14be38c-0d5d-4af8-ad2a-b10efc4fa3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bgy_sel custom-select psgc_fields</value>
      <webElementGuid>39a0611e-1310-43f0-991c-5dabb9c54df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>b434c6dd-1ffb-43af-8bf0-11812f8e80db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_brgy_change(this)</value>
      <webElementGuid>70eb7199-2bd2-4de4-b010-d9cfb8dce644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Barangay -Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBurolBuayang BatoDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J. RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-asaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-wack Greenhills</value>
      <webElementGuid>7994ed0e-d926-4737-9df1-9b5aa73ec4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_barangay_ha&quot;)</value>
      <webElementGuid>7d0d325f-3eb6-4472-9adb-4f9eeb5a4905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>dd8cf970-1ab0-4e15-a49c-3e12a6a65860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_barangay_ha']</value>
      <webElementGuid>990a4bf1-405c-4379-b675-0719f3712319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[4]/div/select</value>
      <webElementGuid>d111b2e7-7753-495c-b5b7-dae94313afa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[28]/following::select[1]</value>
      <webElementGuid>0e17c129-6696-4534-976d-5368a24c5203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Barangay.'])[1]/preceding::select[1]</value>
      <webElementGuid>cb0efdc3-a364-44c4-b031-ae74bcf7d488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[4]/div/select</value>
      <webElementGuid>7283a929-e466-4e65-8dde-0561e022b660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[barangay]' and @id = 'select_barangay_ha' and (text() = '- Select Barangay -Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBurolBuayang BatoDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J. RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-asaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-wack Greenhills' or . = '- Select Barangay -Addition HillsBagong SilangBarangka DriveBarangka IbabaBarangka IlayaBarangka ItaasBurolBuayang BatoDaang BakalHagdang Bato ItaasHagdang Bato LibisHarapin Ang BukasHighway HillsHuloMabini-J. RizalMalamigMauwayNamayanNew ZañigaOld ZañigaPag-asaPlainviewPleasant HillsPoblacionSan JoseVergaraWack-wack Greenhills')]</value>
      <webElementGuid>9cc1739d-39cb-4f96-9c7f-53bd6a7133a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
