<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Province -AuroraBataanBulac_24d277</name>
   <tag></tag>
   <elementGuidId>8e6bf3ca-c9f6-4c7d-8739-f65c0f46310e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_province_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_province_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50263504-9777-47e3-bd32-8043fdd8a9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[province]</value>
      <webElementGuid>e14db887-83ac-4d81-8ac4-dd89bb4987a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_province_ha</value>
      <webElementGuid>a0a414c0-5a79-4d21-bbf1-fb03d862b6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control psgc_province custom-select psgc_fields</value>
      <webElementGuid>d53d9ef0-d7ed-4bb1-9097-7843550e0d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cityid</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>529c084f-0ee8-430f-8607-82c3aad122ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>434b9b66-ecc8-4df5-8136-46dee7aa0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_province_change(this)</value>
      <webElementGuid>96d9dc7f-e4fa-48fd-b688-25625d1d465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Province -AuroraBataanBulacanNueva EcijaPampangaTarlacZambales</value>
      <webElementGuid>f2a009fb-a427-488a-8d22-805f11b7db5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_province_ha&quot;)</value>
      <webElementGuid>895cad16-daa3-4494-acb4-5b07f51c2d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>47c98854-2292-4585-97d8-2ffce685348f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_province_ha']</value>
      <webElementGuid>5f90f64d-632a-426e-aa14-d08fc476bfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[2]/div/select</value>
      <webElementGuid>7c9b0810-c5c1-46e3-9ebb-5b8b0bc0530a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[26]/following::select[1]</value>
      <webElementGuid>0fcf382a-dfd3-4b15-b761-764bcd471623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Province.'])[1]/preceding::select[1]</value>
      <webElementGuid>f7cbcb7c-ae29-4654-937b-f40b881b165a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>9c4a39cf-5aed-4804-9a87-94568caa8fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[province]' and @id = 'select_province_ha' and (text() = '- Select Province -AuroraBataanBulacanNueva EcijaPampangaTarlacZambales' or . = '- Select Province -AuroraBataanBulacanNueva EcijaPampangaTarlacZambales')]</value>
      <webElementGuid>08c76466-4405-4ed2-97c2-d9fc22f3a40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
