<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Barangay -San AgustinSan Ba_11df06</name>
   <tag></tag>
   <elementGuidId>cf024be5-6a18-4422-bae2-03bcc5c6d54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_barangay_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_barangay_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1bdde48c-4030-4071-912f-f8df37165beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[barangay]</value>
      <webElementGuid>47f1bbcc-b2ea-45a5-a89e-b25b7b3e0cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>aef883a2-eda3-49a3-b119-0838ed77cde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bgy_sel custom-select psgc_fields</value>
      <webElementGuid>4be8e9ff-03b8-4ab4-bcd4-5e78966072ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>9220a522-0aa7-4861-b652-5a6d41393037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_brgy_change(this)</value>
      <webElementGuid>ddd7c7b9-54b0-42a8-804f-435d44e9bc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Barangay -San AgustinSan BartolomeSan IsidroSan Joaquin (Pob.)San JoseSan JuanSan NicolasSan PabloSan PedroSan RoqueSanta LuciaSanta MariaSantiagoSanto Rosario</value>
      <webElementGuid>10d581c2-02d6-41b4-910c-fb266ef385fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_barangay_ha&quot;)</value>
      <webElementGuid>5a242914-ba06-4765-8b29-eb8efc10f962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>4be41670-9eca-4657-8429-945bebafa506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_barangay_ha']</value>
      <webElementGuid>c044c135-e54e-4edc-aa66-00fcd497025c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[4]/div/select</value>
      <webElementGuid>11dcfe07-e8dc-4411-b89b-581fff223f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[28]/following::select[1]</value>
      <webElementGuid>b025c371-fffc-4ea5-b2b9-e46555964c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Barangay.'])[1]/preceding::select[1]</value>
      <webElementGuid>e52de64a-61ab-4205-bdbf-78ec3e9e35fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[4]/div/select</value>
      <webElementGuid>f175ec92-3d1c-4e74-8c13-ef35b3c2a904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[barangay]' and @id = 'select_barangay_ha' and (text() = '- Select Barangay -San AgustinSan BartolomeSan IsidroSan Joaquin (Pob.)San JoseSan JuanSan NicolasSan PabloSan PedroSan RoqueSanta LuciaSanta MariaSantiagoSanto Rosario' or . = '- Select Barangay -San AgustinSan BartolomeSan IsidroSan Joaquin (Pob.)San JoseSan JuanSan NicolasSan PabloSan PedroSan RoqueSanta LuciaSanta MariaSantiagoSanto Rosario')]</value>
      <webElementGuid>9e64aa01-ef51-466d-998c-01e9b611fbb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
