<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select City -ApalitArayatBacolorCa_68478a</name>
   <tag></tag>
   <elementGuidId>de36ef42-79a4-4dbc-87cf-7c4350faef0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_city_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_city_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7fb09f53-9801-4740-a10b-12b8afd67811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[city]</value>
      <webElementGuid>24854b43-bc2a-40b3-aaf0-f40fbad6df38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>404b4f8b-4f30-4401-b83e-b7f1f487a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control custom-select psgc_fields</value>
      <webElementGuid>7b2168b2-a502-4ad2-8619-42d01cbad542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>fa401f1c-c752-4afe-919a-499e43675e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brgyid</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>be3119ec-e9c9-4f57-9a56-0bba19c75e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_munci_change(this)</value>
      <webElementGuid>ef6808c9-f3ce-4093-936a-a35c8d4f2f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select City -ApalitArayatBacolorCandabaCity of San Fernando (Capital)FloridablancaGuaguaLubaoMabalacat CityMacabebeMagalangMasantolMexicoMinalinPoracSan LuisSan SimonSanta AnaSanta RitaSanto TomasSasmuan</value>
      <webElementGuid>a18f29c4-74d3-4e11-b5af-a84e3aa7b7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_city_ha&quot;)</value>
      <webElementGuid>341b34cd-e03c-4da8-9a23-0ae18c9a40d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>9058e749-3979-4ca9-8ab1-d374c59d16f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_city_ha']</value>
      <webElementGuid>d7e13c29-d773-4a37-9ae5-e33c4055e99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[3]/div/select</value>
      <webElementGuid>b7dffdd0-de22-4783-8d40-c76ebb6d5f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[27]/following::select[1]</value>
      <webElementGuid>7771b071-ee21-4367-87f6-ff306f0efd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a City.'])[1]/preceding::select[1]</value>
      <webElementGuid>9222dcea-7d6f-466f-b6f5-d3776fe64c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>de363bd1-1e97-4822-a0ff-e87edcd8c907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[city]' and @id = 'select_city_ha' and (text() = '- Select City -ApalitArayatBacolorCandabaCity of San Fernando (Capital)FloridablancaGuaguaLubaoMabalacat CityMacabebeMagalangMasantolMexicoMinalinPoracSan LuisSan SimonSanta AnaSanta RitaSanto TomasSasmuan' or . = '- Select City -ApalitArayatBacolorCandabaCity of San Fernando (Capital)FloridablancaGuaguaLubaoMabalacat CityMacabebeMagalangMasantolMexicoMinalinPoracSan LuisSan SimonSanta AnaSanta RitaSanto TomasSasmuan')]</value>
      <webElementGuid>e0fb88f8-2830-41c9-a971-b3cab6fa3bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
