<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_input_username</name>
   <tag></tag>
   <elementGuidId>50f7bdf6-37bb-4d9e-86e3-f68f4a60e90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca1a6dbe-4cd4-45ce-9990-ed89374874ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7b03781-bf42-4e1b-bc98-a375af39bdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1daa4f21-420e-4423-84e8-ae64a19b72f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>27bca3d3-70d6-41f0-b82b-f45e5575213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>67d8f5b3-0a2a-4df4-b565-a20356ef52a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@email.com</value>
      <webElementGuid>4d0ea23b-5910-4fac-8a6c-d94c7cad9562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_username&quot;)</value>
      <webElementGuid>65def182-e6ed-4459-bddb-9ed374435298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_username']</value>
      <webElementGuid>f6ee4773-c46d-47c9-8069-5aa6eec445d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_div']/div/input</value>
      <webElementGuid>7b420013-c9d1-430d-b16b-ef333ef50918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>41f7c21f-bce6-4795-86b2-c9c2cd77b19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_username' and @name = 'input_username' and @placeholder = 'example@email.com']</value>
      <webElementGuid>85c54b7e-a17e-4209-83b5-26274c606e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
