<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CANCEL</name>
   <tag></tag>
   <elementGuidId>1beba21a-9eca-4641-a58a-89432ecd0e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-large.bold.w-100.h-fit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[71]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5c08a8e-2ca9-4e4f-b171-d3716613e076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>671399f4-14e7-495e-8aa2-2a2053f83789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-large bold w-100 h-fit</value>
      <webElementGuid>7a5ffb3b-8cfc-4cf8-9aa5-45d5268d5f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4be68526-7cd3-4c52-bd3c-d3716e57fecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>12562e19-6e3a-4bb2-9ad6-68b2c4a157e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pinGoogleMapModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered w-100&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body p-0&quot;]/div[@class=&quot;d-flex flex-wrap w-100&quot;]/div[@class=&quot;d-flex flex-column col-md-4&quot;]/div[@class=&quot;d-flex flex-column h-100&quot;]/div[@class=&quot;d-flex flex-column&quot;]/button[@class=&quot;btn btn-secondary btn-large bold w-100 h-fit&quot;]</value>
      <webElementGuid>4bee455e-7d15-4315-9d60-252d10c5d789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>3d096def-3dfe-41ee-ac00-26397076c38e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[71]</value>
      <webElementGuid>f6e80b4b-aa8a-4e1c-9d74-761c64c4a929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinGoogleMapModal']/div/div/div/div/div[2]/div/div[3]/button[2]</value>
      <webElementGuid>cce9d70d-dcd2-47a0-9b83-c53827930232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCEED'])[1]/following::button[1]</value>
      <webElementGuid>e0d787f2-4dd8-474d-81b6-5d332ef993ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::button[2]</value>
      <webElementGuid>53adc62c-2684-4652-9949-41e30ae78820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Settings'])[1]/preceding::button[1]</value>
      <webElementGuid>04dba526-431c-4274-893c-28bc844ca875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>ba2b9c63-ea88-4615-bfd7-3aca39ab5b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>4aa3b448-ed46-46d2-b573-407b98c0943c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
