<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PIN LOCATION ON GOOGLE MAP</name>
   <tag></tag>
   <elementGuidId>65307e49-6c63-4c40-9f57-b7794e7987b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin_loc_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pin_loc_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ef7d075-ac18-4bd1-9f2b-4494329ffaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dff5dea5-d697-4b9b-ad31-3272a6e83c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin_loc_btn</value>
      <webElementGuid>0eb62dfe-79db-4618-a149-ae7a97842020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>965598ad-f7aa-409e-a21c-27c2e5705b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-xs body-lg semibold w-fit</value>
      <webElementGuid>fd85ac6c-42e2-44bf-8dd0-deefde8af2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PIN LOCATION ON GOOGLE MAP</value>
      <webElementGuid>54630239-bda1-4371-8fea-c8a387860382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin_loc_btn&quot;)</value>
      <webElementGuid>ee113ab9-a6e6-40a3-8a48-9371f601c879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>0415e257-c537-4ca5-bcb3-7136efe66317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pin_loc_btn']</value>
      <webElementGuid>012d51c1-e754-4472-a16e-4983044c994c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[8]/button</value>
      <webElementGuid>99f693da-4cb1-4bc4-bcdd-58bd6d0e2668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid field. Please enter proper zip code.'])[2]/following::button[1]</value>
      <webElementGuid>a53fe658-280d-4cd6-b8ea-0b782f8ef2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[2]/following::button[1]</value>
      <webElementGuid>eb5bf919-bc17-45a6-a73e-174eedbecd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button</value>
      <webElementGuid>b74013e5-55ff-45b5-8c3f-242cafa44109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pin_loc_btn' and (text() = 'PIN LOCATION ON GOOGLE MAP' or . = 'PIN LOCATION ON GOOGLE MAP')]</value>
      <webElementGuid>4bd0e355-b3ba-422f-adc8-e1103af41f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
