<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframepage-content-wrapper</name>
   <tag></tag>
   <elementGuidId>6721f577-4477-49f8-9307-b8595da2a118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e048baea-adc4-4c4d-982a-15d1e23828c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>986b0b4b-c4c8-45f8-900a-155561b968a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX</value>
      <webElementGuid>6c54f2f0-d6aa-489d-9e1d-d6720f0c6a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>944cdae8-ad21-4a9e-8ce8-83dbfe3959db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>a5c0fe40-684f-4ce6-9405-808c49d2931c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>b95e7441-a919-4ad0-8306-13368c3501f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>941e258e-8808-4933-bf67-1791f1e111de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX']</value>
      <webElementGuid>36d53cd0-b2f8-4d71-b2f1-94e9ac971349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
