<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ONLINE SERVICES_img-fluid banner-image _ba0b3c</name>
   <tag></tag>
   <elementGuidId>75c63ebc-b173-4e88-a028-563ecbc4a4e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.banner-image.service-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8f47c5d-d62e-4463-9ef5-816bde0265f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png</value>
      <webElementGuid>db132850-4f42-4c2b-aa89-5327a13f3023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid banner-image service-icon</value>
      <webElementGuid>74db26cf-2bfc-4e9a-bed2-694224894efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content-wrapper&quot;]/div[@class=&quot;page-content-wrapper&quot;]/main[@class=&quot;container-fluid text-center container-padding d-flex flex-column aos-init aos-animate&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center&quot;]/div[@class=&quot;col-sm-3 service-card p-0&quot;]/a[@class=&quot;d-flex flex-column align-items-center w-100&quot;]/img[@class=&quot;img-fluid banner-image service-icon&quot;]</value>
      <webElementGuid>52a2e877-8acf-4f3a-a7a6-e145a1d539d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png')]</value>
      <webElementGuid>8718d8eb-b084-48a7-8d92-04a3833b9995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>d6d858a2-0bc0-4cf8-8837-b712e2a0279c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png']</value>
      <webElementGuid>4e0e1d4a-4b1b-4a69-877c-2a215745bb9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
