<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross Floor Area of Building (sqm)_tx_aa6ffc</name>
   <tag></tag>
   <elementGuidId>21f9c907-0cea-444e-bf4a-4f36f1b0ca87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_gfab_sqm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_gfab_sqm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d677d7e-bdbd-4a80-ac43-d65e3712c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9869f73-cc2f-42bd-ad91-e4ec8f95de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>62aa9143-3233-4d99-8692-2249c15e98ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_gfab_sqm</value>
      <webElementGuid>bb4412d4-5205-4cb3-9fc1-c2643c12a524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[gfab_sqm]</value>
      <webElementGuid>d7802d66-8130-47e0-8496-755613c56566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>471a2785-9eb1-461f-b532-6cd8cdc95ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>50e282ed-3d23-487f-8727-4829755d4cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_gfab_sqm&quot;)</value>
      <webElementGuid>b285dece-9380-463a-8fda-a9266debeb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>a7bb5379-57eb-4008-9b5e-863413d49ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_gfab_sqm']</value>
      <webElementGuid>31c7a3a7-945f-4805-ba75-f0092b713027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>c99a7ffa-7b36-4b07-80cb-190c7bea7b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>c34ec48a-68dd-4b22-8e34-704536d126f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_gfab_sqm' and @name = 'txt_lcinfo[gfab_sqm]']</value>
      <webElementGuid>2a20a7a3-cb2c-489e-aa89-c84bc16e8dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
