<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfoproperty_owned</name>
   <tag></tag>
   <elementGuidId>da976514-3aa5-4aee-92e0-f9e744e6d86d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_dyotp_yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_dyotp_yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fb64bd4-e253-4d44-a55e-b93c31524315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aa2b0f04-4d00-4990-b4dc-99f5e5e341f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_dyotp_yes</value>
      <webElementGuid>211aecde-3f30-4f33-8d03-8293420225d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_lcinfo</value>
      <webElementGuid>e700ead9-69f2-423d-8bed-1dee24937ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[property_owned]</value>
      <webElementGuid>689efbd0-531c-43a3-bb28-ec1df43082a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_dyotp</value>
      <webElementGuid>90672ef3-608e-4a36-a2e2-829d3480f904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0cfe17c3-4be1-4acb-951f-d1a1c6eb28c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_dyotp_yes&quot;)</value>
      <webElementGuid>57dd2922-a4b4-461c-82f8-2a387cd1c952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>1bec2f35-d8b4-4310-b2ba-6f208224cfcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_dyotp_yes']</value>
      <webElementGuid>11a9bc87-666e-4d49-8e3c-8376703b9084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dyotp_section']/div[2]/div/input</value>
      <webElementGuid>e5682605-5b1c-43ec-9fd1-055f5f6cd701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/input</value>
      <webElementGuid>a1df34a1-5a69-4cde-a239-02dc44bb86dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_dyotp_yes' and @name = 'txt_lcinfo[property_owned]']</value>
      <webElementGuid>2012e547-396f-4962-b2c6-de10e6b9c9b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
