<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfophno_case</name>
   <tag></tag>
   <elementGuidId>17625973-bbb5-4f6f-b72c-27ed5cf0c194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_phno_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_phno_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ee10c27-078f-475f-95de-f0947e6e7594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30c74c4a-9e8a-4c95-855a-58b46098bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>9844a295-bf40-4f35-a640-7cd413e6f0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_phno_case_2</value>
      <webElementGuid>800e0b6b-6775-4bc0-8b2f-03b493acfbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[phno_case]</value>
      <webElementGuid>4ec418ef-5d85-4325-8788-205e0fcba5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>9XX-XXX-XXXX</value>
      <webElementGuid>af810f60-dee3-48b7-8ba6-9bf8f7d13e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[9][\d]{9}</value>
      <webElementGuid>1b0ca78c-6fd7-4c88-a0b0-5ca33e52d99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>369d9e8a-ad92-4f2b-bfc6-402bc59b0a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>768829a7-de93-4b82-a57d-c8215810ce20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_phno_case_2&quot;)</value>
      <webElementGuid>2fcad609-5186-4f94-9ddc-33c665bfaf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>80d40414-38d9-4aac-86d6-fccf5f875731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_phno_case_2']</value>
      <webElementGuid>a924bbc3-cbf3-4e47-98c2-8addf9e2c43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>3b94af01-b667-44f2-904d-2f0adf3f6c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>2d0f2f3c-b8c1-490f-861a-c72a9bed639e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_phno_case_2' and @name = 'txt_lcinfo[phno_case]' and @placeholder = '9XX-XXX-XXXX']</value>
      <webElementGuid>1caf04c4-0f4b-4a94-a634-b40e9a25905c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
