<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Block No_txt_lcinfohblasubf_lpe</name>
   <tag></tag>
   <elementGuidId>8b563695-78a8-4bb7-b690-8ee3d7eb6950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_blockno_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_blockno_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14d84165-5ebc-451b-bada-0006a6538d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92ffdf9c-c121-463d-88d6-2cf8a1cbb755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>07af491f-63fa-4bdd-83d7-e48f1815adef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_blockno_lpe</value>
      <webElementGuid>92633357-5de4-4534-88d2-ed97e09adb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[hblasubf_lpe]</value>
      <webElementGuid>8dd7ee18-74c4-48b5-93a8-6b5cc25cc42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>83f2c933-0339-4b88-9021-13c8f85c2536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>addressfields</value>
      <webElementGuid>15bf1196-6bab-493e-96d3-081a1561e397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_blockno_lpe&quot;)</value>
      <webElementGuid>b09f0a8f-e0eb-4c8c-86a4-6d77922699a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>09bdefd1-e214-4b9b-836b-b959907ea80a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_blockno_lpe']</value>
      <webElementGuid>d8a26957-e713-4e5c-bbfe-22c878583486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>57015e52-c718-43cc-8ced-80157f549d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>d04c60b7-2ba2-4286-b970-372fdbac1d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_blockno_lpe' and @name = 'txt_lcinfo[hblasubf_lpe]']</value>
      <webElementGuid>f21debbe-6c57-432b-be78-4fb202eaa187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
