<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfotctno</name>
   <tag></tag>
   <elementGuidId>909c3fff-66d8-4781-9ff6-354201a261df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_tctno_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_tctno_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d96c24c5-be17-4ec2-9954-0ae3e2d324dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d3fe6a2-5ba0-43ec-a60d-c66add914ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac94d960-41e4-45e6-b14d-ab4ba9de2492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-class</name>
      <type>Main</type>
      <value>text_tctno</value>
      <webElementGuid>66d539dd-8ce1-47ca-a964-337ae76a0c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_tctno_1</value>
      <webElementGuid>87cf214d-16d5-437a-a7e0-ec60e7ba3bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[tctno]</value>
      <webElementGuid>ba9c7ddf-96da-4afd-8927-014c1b2c456b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{1,}</value>
      <webElementGuid>41870d5a-7830-4b6b-834d-a88b0eed8772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>27d5508d-e015-482b-b226-5e0f5677c617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_tctno_1&quot;)</value>
      <webElementGuid>eb7863df-858b-414c-8a54-93f961a7037d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>43fe48c8-2852-4a2d-bcc6-8d8ab076079a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_tctno_1']</value>
      <webElementGuid>65c76c96-0163-4d54-bd6d-6b2cffdc58f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tct_container']/div/div/div/input</value>
      <webElementGuid>8b6ce209-6b5e-4119-9729-8dd2ff223010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>0e2b3f73-abc7-4bf1-ba71-e005da923661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_tctno_1' and @name = 'txt_lcinfo[tctno]']</value>
      <webElementGuid>960247e2-44e7-4add-9367-0690a0e0707a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
