<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfolotarea</name>
   <tag></tag>
   <elementGuidId>b52d27b5-56a2-4f13-b928-1f76d3fe0f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_lotarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_lotarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11723014-e2c6-4ed9-b559-1f062881da16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cae191c1-2376-46e9-b3aa-2b3dd89bbe78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-valid</value>
      <webElementGuid>20a24ec4-19d7-4448-901a-5c61bcca2b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_lotarea</value>
      <webElementGuid>7f5c4b15-1cee-4272-b41a-c0d2c1a2c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[lotarea]</value>
      <webElementGuid>0c1bdd4a-c3a9-42c7-adee-4c3027f23af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>f041658d-0f96-4a15-b6fd-d69127e56fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>b08bdefe-1183-4f08-a875-2d09338da425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_lotarea&quot;)</value>
      <webElementGuid>c937a638-cbb8-463c-b234-664206b82693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>74072efe-6122-41c0-9ab8-0e3847b384da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_lotarea']</value>
      <webElementGuid>86901056-0ac6-410f-aca1-9c1bcc23dee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[3]/div[2]/div/input</value>
      <webElementGuid>8f3c1c4b-71af-4232-ae23-b3b7711153d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div[2]/div/input</value>
      <webElementGuid>73b383ef-9ccf-4321-b9a9-f39ae8f1a2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_lotarea' and @name = 'txt_lcinfo[lotarea]']</value>
      <webElementGuid>f9eeba8c-aa7f-4e3f-a8f6-44662f58bb7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
