<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonature_of_application</name>
   <tag></tag>
   <elementGuidId>36b68c7f-7c97-460c-9264-ebb1b5210dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_nc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_nc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8f25cc2-14de-462b-af8c-069280cdd867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>06eda0cf-29c5-4648-83f4-57818bc786e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_nc</value>
      <webElementGuid>4c573f0a-1185-437a-a1bf-a96d52ac6855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_lcinfo</value>
      <webElementGuid>5482f09c-5103-4b0d-a33d-dedbe322fa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nature_of_application]</value>
      <webElementGuid>4ed7c63a-8239-48cd-935e-2f056ac6904a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_nature_of_application</value>
      <webElementGuid>6cf990df-6f61-4d2a-8e6a-843cc77b8060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>951e1822-989f-491a-8ca6-1c0c32460d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_nc&quot;)</value>
      <webElementGuid>8953ea27-3857-4c7c-ab36-1d01abfb4cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>701cadf5-82f1-40b3-b065-520f92b1ac0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_nc']</value>
      <webElementGuid>7b4cdb70-29b0-4990-a686-034bf0aa54db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nature_of_application_wrapper']/div[2]/div/input</value>
      <webElementGuid>8936c23d-2ab9-4434-a9aa-7f23fcabafe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>46d662e6-875b-4ef4-b8aa-55d7e7edf095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_nc' and @name = 'txt_lcinfo[nature_of_application]']</value>
      <webElementGuid>9f99f33e-1619-427f-90bf-7150aec00465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
