<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonopgm_ln</name>
   <tag></tag>
   <elementGuidId>6a94da1d-72b0-4ed4-b978-3a4ddd5a3f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nopgm_ln</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nopgm_ln']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eca8cc01-90b9-4f89-bff9-06599631e053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc568d42-be85-4070-b7fb-1cf558a6a219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>d56e2c81-1d99-4da9-bf9e-20a99c66336c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nopgm_ln</value>
      <webElementGuid>9e2392ca-6888-4cb3-a95f-24ac04a1335c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nopgm_ln]</value>
      <webElementGuid>2a50705a-7795-46ac-88d7-9b3929bf1cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\-\.][\u00F1\u00D1a-zA-Z\s\-\.']+</value>
      <webElementGuid>8207bb63-7755-4975-978d-4764405c7317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>personname</value>
      <webElementGuid>9152490a-550a-42d8-bec3-030f56d8dd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nopgm_ln&quot;)</value>
      <webElementGuid>312bafd8-39da-4b24-8b31-2eed44f42650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>d18031a7-b14e-4c73-8643-d44e6e37c859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nopgm_ln']</value>
      <webElementGuid>d1f7eef1-6fe5-4fb8-ad9c-161bcfa1db28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[2]/div/input</value>
      <webElementGuid>25d0046e-4a39-4947-866c-8ac868d0c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>b30b5585-f953-4e07-b1cb-8e8a9440bf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nopgm_ln' and @name = 'txt_lcinfo[nopgm_ln]']</value>
      <webElementGuid>3bb1697c-c6de-44a2-a24e-daefe00294de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
