<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please upload a file here_txt_lcinfoappby</name>
   <tag></tag>
   <elementGuidId>0249b9e1-ac86-4754-bc27-2e5e52064969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_appby_owner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_appby_owner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af6f01f9-5932-48d2-943d-aed62f687f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>24725c58-677b-4177-9bf0-3549ee86898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_appby_owner</value>
      <webElementGuid>9513a108-169d-4de5-af84-70dc5f76aeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[appby]</value>
      <webElementGuid>794cafdb-e0ee-483b-b87f-4248f6bf4b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_appby</value>
      <webElementGuid>1ebed21b-bb1d-4ba6-925c-03c9280bb079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>49fe716c-c4cb-4adf-9e5a-50e9f24b3318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_appby_owner&quot;)</value>
      <webElementGuid>d4c2942e-e043-4853-8e58-4510f02b5c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>9384eca3-0202-4571-9c70-fc4236502a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_appby_owner']</value>
      <webElementGuid>fa7c123a-3633-48e3-a855-9deec3c4b5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[4]/div/div/input</value>
      <webElementGuid>30bb9f9f-c4f5-42af-9e06-65ceeaefaf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>e2412816-5d0b-4988-9bcf-27cfb9da1b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_appby_owner' and @name = 'txt_lcinfo[appby]']</value>
      <webElementGuid>e73c549e-0e93-4491-8f22-e9e70f1b16a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
