<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name of FirmCorpCo_txt_lcinfonfcc</name>
   <tag></tag>
   <elementGuidId>6fdfe060-57ba-4aea-bf05-1055a915a699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nfcc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nfcc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e351eee-6dcc-43f9-9a19-3cfbd5a72dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b24ea805-dad2-4f22-8b07-e2ccc5f32a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>3ba23750-14c8-4bd9-b796-51ad5701dfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nfcc</value>
      <webElementGuid>514a7ca0-17aa-4c6e-aef0-73cc60027c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nfcc]</value>
      <webElementGuid>fd5665d1-1fec-49dd-8779-b37a687de827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>a602a199-f009-43cd-95c0-c66460807bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>limitedtext</value>
      <webElementGuid>647bb81c-94b4-452c-81d9-7f90825ca10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nfcc&quot;)</value>
      <webElementGuid>8699865e-4652-43e0-beff-5ca7a8222113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>a6ad744b-4ceb-4a5d-951c-e7785b90dff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nfcc']</value>
      <webElementGuid>cf266416-fbed-47c9-8e91-16d2260e647b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[5]/div/div/input</value>
      <webElementGuid>fd38bc9b-8a67-4921-a4c4-80ca914f1909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>aeaa8548-442b-4518-80f8-9de8ce83fdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nfcc' and @name = 'txt_lcinfo[nfcc]']</value>
      <webElementGuid>e5f93220-bfc6-4f99-a9ed-6e103c1d964a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
