<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_txt_lcinfozipc_lpe</name>
   <tag></tag>
   <elementGuidId>9b75e95b-c829-4316-8f17-68c310ba60a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_zipc_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_zipc_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c76b8a1a-823d-47b0-937f-52b39fd8f8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e57ae02d-7292-41f9-9ff8-659b58126e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>cd53e53b-72c9-454b-8a28-e2a24f8957a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_zipc_lpe</value>
      <webElementGuid>f7630b8b-859f-4818-99b0-8dadc99903d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[zipc_lpe]</value>
      <webElementGuid>86a16528-cb84-4341-b306-0e94bf9efe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{4}</value>
      <webElementGuid>0bce4e91-c090-4713-bc8e-5b04f80a4ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>0b3b0d33-cee0-4f05-964b-bfac170c44b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXX</value>
      <webElementGuid>f63617da-7925-40c7-be70-214a31e7d0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>91de55cd-f385-4262-8156-6f45c8c0b6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_zipc_lpe&quot;)</value>
      <webElementGuid>35c7b2b6-1f9e-4fc4-9a8b-02353ef2f416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>036c662a-de06-49ab-906d-55d8f50c28f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_zipc_lpe']</value>
      <webElementGuid>e72d0c4d-7ae0-45fd-8d21-2606520aff07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>5f0b22ff-45c3-4a01-8573-cc1ad0692619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>4a6c3adf-a45f-4578-90b3-85d121621cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_zipc_lpe' and @name = 'txt_lcinfo[zipc_lpe]' and @placeholder = 'XXXX']</value>
      <webElementGuid>30cae7d2-ff8b-474b-bdef-46cdf3376a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
