<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invalid field. Please enter proper te_3469a4</name>
   <tag></tag>
   <elementGuidId>8b3e0fee-6449-4734-8d58-473c497c273a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox_middle_name_nopgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox_middle_name_nopgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a9a8996-5267-41f5-a859-f6d686fa0402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cb135987-31ea-4ee9-878b-fc35e9a6c727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input txt_lcinfo</value>
      <webElementGuid>a9bae311-55c4-402e-88d5-7f9b374218ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox_middle_name_nopgm</value>
      <webElementGuid>27fcb71a-34f7-4ea3-9b3e-28fc9f95e0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[no_middle_name]</value>
      <webElementGuid>37c1164f-9ad2-40c7-b8c0-e60c83899bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_middle_name_nopgm&quot;)</value>
      <webElementGuid>1dbe168b-56d8-4c19-97e4-569f353750cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>8df0f911-bfa5-4996-a29b-28275229af6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox_middle_name_nopgm']</value>
      <webElementGuid>12ccafcd-95fc-4ead-b61d-d8269b675638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>ad7dba0e-160c-4296-8174-d9f0a75d13f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>d8f5a041-d007-475a-95cd-cbac1b9d3d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox_middle_name_nopgm' and @name = 'txt_lcinfo[no_middle_name]']</value>
      <webElementGuid>64879055-6483-466d-b49d-e960b6b2a515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
