<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonopgm_fn</name>
   <tag></tag>
   <elementGuidId>716645a0-1a3f-4a6f-b8ae-b1303bf387e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nopgm_fn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nopgm_fn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3ebac14-ef50-4b8b-ae00-fa9d1ce45c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e932be63-387b-4bd7-9430-d272e1c7bf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>6ae8d6ab-f110-4d6d-9780-447ba1cb645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nopgm_fn</value>
      <webElementGuid>e8e4779d-a938-4430-b52e-e8b69192ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nopgm_fn]</value>
      <webElementGuid>fbe1c289-93d1-4df5-be0e-c750a5635030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\-\.][\u00F1\u00D1a-zA-Z\s\-\.']+</value>
      <webElementGuid>4dbcac73-cddd-48e6-af40-99ab6143eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>personname</value>
      <webElementGuid>5e3a202d-0705-4b9a-b361-302770e71d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nopgm_fn&quot;)</value>
      <webElementGuid>ebc6ab69-0336-4651-a9a1-030dca795cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>1e7d8e89-0ea0-492d-8a11-fbcd0c54d205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nopgm_fn']</value>
      <webElementGuid>4ba7d3ce-f894-4972-9232-e8314ed2d325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div/div/input</value>
      <webElementGuid>fb29398f-3600-48da-aa5c-3663e4700761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>0972a8ee-adaa-4741-ac2d-f612137e72d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nopgm_fn' and @name = 'txt_lcinfo[nopgm_fn]']</value>
      <webElementGuid>514a1b17-2dd2-41b4-a209-85135ff52a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
