<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_INFORMATION_txt_lcinfoapp_position</name>
   <tag></tag>
   <elementGuidId>176435fe-b235-4814-994e-6f7d4505e985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio_applicant_owner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_applicant_owner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c5de9be-0daf-4648-bd77-192280abc190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bf767b46-c50b-40cd-a623-6426765def78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_applicant_owner</value>
      <webElementGuid>df0c2b20-ba99-4adb-ac68-beae47085b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[app_position]</value>
      <webElementGuid>0bd43e21-bb3c-4b4d-b04e-c708c5ced2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>radio_applicant_profile</value>
      <webElementGuid>a1344bdb-2d38-46b1-929c-eab3143fb1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio_applicant_profile</value>
      <webElementGuid>b40033ce-ba21-4815-9601-25811278325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f5e3f53d-b9e4-4ae7-bf66-0f353898d8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_applicant_owner&quot;)</value>
      <webElementGuid>c0265c39-34fc-40d8-8ed3-7ccf41302151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>5668127c-4dfe-4646-b3c2-274fefac5879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_applicant_owner']</value>
      <webElementGuid>66442e2b-99db-41c1-b4e2-f1456e3c2879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[2]/div/input</value>
      <webElementGuid>5eb21f47-723d-46ba-b6fd-b0c9c57998c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>ff615761-1230-4acd-95d6-fcb84967c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_applicant_owner' and @name = 'txt_lcinfo[app_position]']</value>
      <webElementGuid>634d8865-d149-4689-8e05-9fab5ca80365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
