<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfoemail_case</name>
   <tag></tag>
   <elementGuidId>5c1a7175-ab94-4d0a-b88e-bd93bac84847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_email_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_email_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29f8632f-4b1e-4cc9-9921-00ec3aa32aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f3ecb47-c0e2-49b8-ad64-0295e9f8fe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>d62b5782-ab79-4d4b-a45f-a9279bdc1fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_email_case_2</value>
      <webElementGuid>35c9984b-8533-401f-8fbd-b8a89216d5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[email_case]</value>
      <webElementGuid>29775645-6c80-4f73-9bbc-30279f397d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9\-\._%+]+@([a-zA-Z0-9\-]{2,}\.)+[a-zA-Z0-9\-]{2,4}</value>
      <webElementGuid>b696be87-4b1c-41e2-8383-7411dddab7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>aa369e5b-3ad6-42f9-8316-b5014dfb0f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_email_case_2&quot;)</value>
      <webElementGuid>7c360c82-aac6-4da0-bb14-2ac09ef95dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>5f851c83-5256-47e7-9991-b252ebb96ab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_email_case_2']</value>
      <webElementGuid>540ddf79-c9a6-4635-9461-3d2bb07226a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>cb2e663d-b3c4-40e6-a980-9996cec45a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>dde7f935-e29a-4bda-8d70-3b92066763f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_email_case_2' and @name = 'txt_lcinfo[email_case]']</value>
      <webElementGuid>503e64a6-e4a7-4e38-b271-4975f10e109c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
