<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select City -AgooAringayBacnotanBa_f53a49</name>
   <tag></tag>
   <elementGuidId>36244dc5-3a3f-497e-8afc-2fa1a1208fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_city_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_city_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a808927d-2957-4b4b-a83c-6b2ac337f2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[city]</value>
      <webElementGuid>b167d099-e903-4eb4-a6b2-28d4c3e692fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>605cbf41-1c39-49fd-9774-a780291b6fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control custom-select psgc_fields</value>
      <webElementGuid>731ec038-24d8-4dd7-915b-355603bd8698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>8d46d969-b5aa-4eac-be6f-e1bd04b9b672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brgyid</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>881f9df3-ad15-4e22-8002-894a88ed7f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_munci_change(this)</value>
      <webElementGuid>b327e951-2906-4299-874d-0ff6552a781d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select City -AgooAringayBacnotanBagulinBalaoanBangarBauangBurgosCabaCity of San Fernando (Capital)LunaNaguilianPugoRosarioSan GabrielSan JuanSanto TomasSantolSudipenTubao</value>
      <webElementGuid>2ba048e0-83ce-4f48-9b32-d928380db90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_city_ha&quot;)</value>
      <webElementGuid>2e1b6ed6-2ad6-467a-9fc9-3088b7d7feaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>e81270d1-9657-401e-baf3-1c28e36475c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_city_ha']</value>
      <webElementGuid>8b2e3ca4-06b0-46ce-8af9-bec45298d676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[3]/div/select</value>
      <webElementGuid>5b3f1f52-bc12-49a7-9ff3-97691d808936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[27]/following::select[1]</value>
      <webElementGuid>994392c2-4778-430b-be24-a63dc7562b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a City.'])[1]/preceding::select[1]</value>
      <webElementGuid>1554ea55-7c9f-48bf-8140-1bade47693b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>b64c4796-825d-4165-9687-5f20a9ac7cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[city]' and @id = 'select_city_ha' and (text() = '- Select City -AgooAringayBacnotanBagulinBalaoanBangarBauangBurgosCabaCity of San Fernando (Capital)LunaNaguilianPugoRosarioSan GabrielSan JuanSanto TomasSantolSudipenTubao' or . = '- Select City -AgooAringayBacnotanBagulinBalaoanBangarBauangBurgosCabaCity of San Fernando (Capital)LunaNaguilianPugoRosarioSan GabrielSan JuanSanto TomasSantolSudipenTubao')]</value>
      <webElementGuid>dea7c00c-3f49-4eba-9d64-ead38d9d5b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
