<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Province -Ilocos NorteIloco_87f89a</name>
   <tag></tag>
   <elementGuidId>ba8ada5d-d7ee-4da9-a2aa-d612e1327523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_province_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_province_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>55bb2ec8-3d43-4657-b237-39ba6be7bd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[province]</value>
      <webElementGuid>02c69393-2bb4-448f-877a-23eb7c24b222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_province_ha</value>
      <webElementGuid>63b28a8c-b817-4ca0-ae19-20962a761bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control psgc_province custom-select psgc_fields</value>
      <webElementGuid>15acdb5c-4a84-4459-9030-d02848e3a259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cityid</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>e188e48e-45c4-4a76-b327-00a26a5c4021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>539fd19d-949f-4746-9dbd-b149e182e625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_province_change(this)</value>
      <webElementGuid>dbcb3516-13c6-433b-8a8d-f25ac6325da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Province -Ilocos NorteIlocos SurLa UnionPangasinan</value>
      <webElementGuid>40d58fcd-0a93-40ac-8bd5-39fca7dc32ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_province_ha&quot;)</value>
      <webElementGuid>daefb86d-4c54-4a0f-8f69-1394708a2464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>2420e549-764f-453c-be43-8f8b43c529ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_province_ha']</value>
      <webElementGuid>3937e6b2-3e22-49c6-b51f-a63422032f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[2]/div/select</value>
      <webElementGuid>066b91f5-dfb7-4c0c-ad91-3ddbd706493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[26]/following::select[1]</value>
      <webElementGuid>0b3b724b-f0df-4dda-a336-72233baca7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Province.'])[1]/preceding::select[1]</value>
      <webElementGuid>968ec8a2-9ce6-456a-aaa5-85aa22ccbb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6862abdf-f0be-4e42-9711-e159098e4836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[province]' and @id = 'select_province_ha' and (text() = '- Select Province -Ilocos NorteIlocos SurLa UnionPangasinan' or . = '- Select Province -Ilocos NorteIlocos SurLa UnionPangasinan')]</value>
      <webElementGuid>780c84f8-7701-4a64-b79f-d60683a8f7d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
