<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Barangay -AgdeppaAlzateBang_2c7b44</name>
   <tag></tag>
   <elementGuidId>3d941cf9-a3b1-4f37-85e3-329a08b52bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_barangay_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_barangay_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c18b702-52c8-4b99-a6b4-b91e92258537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[barangay]</value>
      <webElementGuid>d28e076f-fd9d-4773-9c05-c28d72513380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>8f363523-edaf-494c-92a7-82b6a48beb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bgy_sel custom-select psgc_fields</value>
      <webElementGuid>a078aa27-b647-423f-bef8-fc19f467f7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>c33ebeb0-3392-4bc9-bfc1-d6dc4a617d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_brgy_change(this)</value>
      <webElementGuid>fec4979f-40f3-4505-a5f1-d59eb992463f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Barangay -AgdeppaAlzateBangaoilan EastBangaoilan WestBarracaCadapliCaggaoCentral East No. 1 (Pob.)Central East No. 2 (Pob.)Central West No. 1 (Pob.)Central West No. 2 (Pob.)Central West No. 3 (Pob.)ConsuegraGeneral Prim EastGeneral Prim WestGeneral TerreroLuzong NorteLuzong SurMaria Cristina EastMaria Cristina WestMindoroNagsabaranParatong No. 3Paratong No. 4Paratong NorteQuintarongReyna RegenteRissingSan BlasSan CristobalSinapangan NorteSinapangan SurUbbog</value>
      <webElementGuid>b0a149e7-bedd-4bc3-a18a-228ccac9227b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_barangay_ha&quot;)</value>
      <webElementGuid>a45f099b-37bf-44ed-8b29-9f378706becc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>f2c653e9-24e9-4d11-b1f4-9ed098c8039d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_barangay_ha']</value>
      <webElementGuid>2618fb8a-baa3-406b-8a9d-9506dda724b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[4]/div/select</value>
      <webElementGuid>0120aca7-dfb8-4422-bef2-cfa65f6d0c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[28]/following::select[1]</value>
      <webElementGuid>fd311ab5-0c88-43b8-b151-80b18500d206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Barangay.'])[1]/preceding::select[1]</value>
      <webElementGuid>8fc3b43c-e724-4ddc-a8b4-cdb5fafd4b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[4]/div/select</value>
      <webElementGuid>4a0e01eb-a91b-4757-8632-f9d11eff26d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[barangay]' and @id = 'select_barangay_ha' and (text() = '- Select Barangay -AgdeppaAlzateBangaoilan EastBangaoilan WestBarracaCadapliCaggaoCentral East No. 1 (Pob.)Central East No. 2 (Pob.)Central West No. 1 (Pob.)Central West No. 2 (Pob.)Central West No. 3 (Pob.)ConsuegraGeneral Prim EastGeneral Prim WestGeneral TerreroLuzong NorteLuzong SurMaria Cristina EastMaria Cristina WestMindoroNagsabaranParatong No. 3Paratong No. 4Paratong NorteQuintarongReyna RegenteRissingSan BlasSan CristobalSinapangan NorteSinapangan SurUbbog' or . = '- Select Barangay -AgdeppaAlzateBangaoilan EastBangaoilan WestBarracaCadapliCaggaoCentral East No. 1 (Pob.)Central East No. 2 (Pob.)Central West No. 1 (Pob.)Central West No. 2 (Pob.)Central West No. 3 (Pob.)ConsuegraGeneral Prim EastGeneral Prim WestGeneral TerreroLuzong NorteLuzong SurMaria Cristina EastMaria Cristina WestMindoroNagsabaranParatong No. 3Paratong No. 4Paratong NorteQuintarongReyna RegenteRissingSan BlasSan CristobalSinapangan NorteSinapangan SurUbbog')]</value>
      <webElementGuid>540c559a-2e7b-434b-9329-6ad14ca44aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
