<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PROCEED</name>
   <tag></tag>
   <elementGuidId>5fb49f71-2bef-478f-b89b-30a6a5241bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_get_address > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_get_address']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d9d3957-e173-455a-80bd-5d53d6bb7356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>e6d3e144-403f-4898-957f-8073f9775256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_get_address&quot;)/span[1]</value>
      <webElementGuid>f2ca2df9-84d3-436d-b56f-6d6179cc08f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>49e66551-5688-4934-b297-fa9e437e01f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_get_address']/span</value>
      <webElementGuid>043a1f12-4838-4c04-8d11-39897f88119d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 359'])[1]/following::span[1]</value>
      <webElementGuid>d3d1382a-2907-403d-9c4f-51507a1c0574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 358'])[1]/following::span[1]</value>
      <webElementGuid>14ade90d-a22e-4e94-8d39-ecd9fc73c5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[2]/preceding::span[1]</value>
      <webElementGuid>6f83dbd9-d937-4c76-9979-bcb26d55be13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Settings'])[1]/preceding::span[2]</value>
      <webElementGuid>6d8e49d7-92b2-4556-8623-b40b09a02466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCEED']/parent::*</value>
      <webElementGuid>e27c385b-5485-47b7-92d1-5be38ff75ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>90a053f1-ee21-460d-9e17-ff76986c7f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PROCEED' or . = 'PROCEED')]</value>
      <webElementGuid>140e53d2-4750-42f5-ab8c-5c5044e49b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
