<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframepage-content-wrapper</name>
   <tag></tag>
   <elementGuidId>48d02d5c-36b6-40c0-8a60-e6a450d6947f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dbf1c9db-be74-41ef-a6c5-b5c644a3c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>e9e87fad-4b59-41e6-b4f1-7e3a03a99c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://adminmandazauqa.unifysyscontrol.com/Homepage/index?UserID=16&amp;UserTypeID=1&amp;as=MTA4fQJJRD0xNnxLZXk9U2FuZG1hbkN5cGhlcnxGTmFtZT1Jbml0aWFsfExOYW1lPUV2YWx8Q29udGFjdD0wOTEwIDgyMyA3e1VzZX</value>
      <webElementGuid>ee7c8b6c-e7fb-4e45-9d49-db9ae3ce592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>7ab9589b-eaf6-43a5-a908-a593f7acbb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>dacee882-2633-416b-8794-c7499e735083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>45e3f607-e8b9-4074-9a4e-5d5c0bdcdb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>40b9d138-8893-4402-9047-3d8ed4b29ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://adminmandazauqa.unifysyscontrol.com/Homepage/index?UserID=16&amp;UserTypeID=1&amp;as=MTA4fQJJRD0xNnxLZXk9U2FuZG1hbkN5cGhlcnxGTmFtZT1Jbml0aWFsfExOYW1lPUV2YWx8Q29udGFjdD0wOTEwIDgyMyA3e1VzZX']</value>
      <webElementGuid>c6ed4d72-ac9b-4abb-aa17-c3ba00bd11cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
