<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_input_username</name>
   <tag></tag>
   <elementGuidId>9e0be4fa-832a-407d-82cc-bb1e57b44f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c429bbe-c822-4796-bcbd-9fd12988a154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f27de64-bd88-463b-ac04-5985afeb25dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>046773e0-9512-4992-81a2-4268023c0a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>4e80f719-511e-495e-9c60-570d310aeffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_username</value>
      <webElementGuid>c59af39e-b2ae-4d62-92f8-72b3af9fb432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@email.com</value>
      <webElementGuid>9b682d11-baee-41d8-8a7a-05f2ea321849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_username&quot;)</value>
      <webElementGuid>34e1e6c2-0b0f-4e52-8683-5694cb0daab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_username']</value>
      <webElementGuid>b6c1a3a2-9201-405c-843f-846b8ae1148e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_div']/div/input</value>
      <webElementGuid>c03db612-b0f5-4d28-982a-79b1da48f5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>923f445c-3213-47ef-9626-06914d477417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_username' and @name = 'input_username' and @placeholder = 'example@email.com']</value>
      <webElementGuid>c3299087-893d-4eea-a4a5-82fef7a47954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
