<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROCEED</name>
   <tag></tag>
   <elementGuidId>ebc449e8-1a9e-48c9-9f0b-3af5008e7f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_get_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_get_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cca15021-b372-4214-b0d8-5f1e6332206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>451f5d93-6a93-46c4-842d-fed5db961ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-large bold w-100 h-fit</value>
      <webElementGuid>88552881-8e90-40b7-9f74-d0cff5c1109a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_get_address</value>
      <webElementGuid>c2a16d41-2d26-4331-b5e6-ca9ae0f0a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>8b210bbb-a516-46fa-aebc-74bf66b34395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_get_address&quot;)</value>
      <webElementGuid>e9d12168-a1d2-4bab-bac8-e899e90216cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>df277a78-dfe2-4248-a535-b63b5d141c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_get_address']</value>
      <webElementGuid>ae11ab9b-7c9a-425d-b6cd-72e8777af0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinGoogleMapModal']/div/div/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>ae0ef302-395b-4d89-96e2-caab46c2bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 765'])[1]/following::button[1]</value>
      <webElementGuid>3651fd65-1669-4860-8162-36878b14acca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[8]/following::button[1]</value>
      <webElementGuid>f56653e1-63fa-4a2a-9339-d866360391c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[2]/preceding::button[1]</value>
      <webElementGuid>40035ae4-7677-4517-8203-97464b864717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>d268484a-d3e8-498a-8431-f18e3370e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_get_address' and (text() = 'PROCEED' or . = 'PROCEED')]</value>
      <webElementGuid>8002e91a-919e-43ab-8537-8b8108657476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
