<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframepage-content-wrapper</name>
   <tag></tag>
   <elementGuidId>a762bdd4-d30b-4a04-8552-df7a23896d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7d0b7f3e-81b2-4451-b184-a6549fbb9a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>6dee4710-02d6-4d65-9f76-8da63a1f12ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX</value>
      <webElementGuid>a551b38f-26e6-4296-a0d6-3df82a8a3b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>0bc8893c-903f-482e-9130-819216b5f22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>83262cdd-b6f2-4c21-a8bf-77c72402d692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>69bc7dbb-5ca2-45f8-8290-b64a709ad5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ef977a8b-41a2-46d8-9ff4-b4f2d2de2998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX']</value>
      <webElementGuid>f97d515c-194c-49b2-bf45-c376a43122bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
