<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ONLINE SERVICES_img-fluid banner-image _ba0b3c</name>
   <tag></tag>
   <elementGuidId>19f17dda-1c40-4557-b8c7-7fc3105ef85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.banner-image.service-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>162863d3-9688-4af5-be1a-e6f5f5be4fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png</value>
      <webElementGuid>35c4c41d-4d85-4aea-8002-4d0bd9640309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid banner-image service-icon</value>
      <webElementGuid>f2b1eeaa-27a9-4bdd-86cd-1d7b87de6fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content-wrapper&quot;]/div[@class=&quot;page-content-wrapper&quot;]/main[@class=&quot;container-fluid text-center container-padding d-flex flex-column aos-init aos-animate&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center&quot;]/div[@class=&quot;col-sm-3 service-card p-0&quot;]/a[@class=&quot;d-flex flex-column align-items-center w-100&quot;]/img[@class=&quot;img-fluid banner-image service-icon&quot;]</value>
      <webElementGuid>9c7b25f6-d7a4-4f4c-88e9-832b12e81251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png')]</value>
      <webElementGuid>ab87eaa1-7fa1-4238-8100-95d5e8e280ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>5bbe4bd0-ec5d-45f0-8c84-d38618367d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://mandacoreqa.unifysyscontrol.com/assets/images/mandaluyong_main/zau.png']</value>
      <webElementGuid>fed0d393-6436-4a99-bef6-99a7248be241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
