<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project Cost_txt_lcinfoprojcos</name>
   <tag></tag>
   <elementGuidId>8b5ab949-bce8-4edb-b901-20732d9b5293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_projcos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_projcos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6092ad8f-b580-472e-a07e-0813b245a9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>593c3419-dd96-4248-a927-d0c2d58c774a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>918c86a0-0ea4-4006-9009-943ee209d4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_projcos</value>
      <webElementGuid>5c5b0516-98cb-432e-af30-b6a81826a7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[projcos]</value>
      <webElementGuid>24101fa9-e1e7-4c8c-af17-c5a0e4266e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>8dd363c0-5831-45a3-ab9b-6be7de5878d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>c666314e-6ab1-49c3-b5dc-09048582f86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_projcos&quot;)</value>
      <webElementGuid>83b78e2b-830b-4a3d-9b87-6c8412d2fbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>d6842adc-287e-4117-8817-b820adaa7a63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_projcos']</value>
      <webElementGuid>8ffe223d-5dba-4035-8886-1601287d49c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[3]/div/div/input</value>
      <webElementGuid>87e61e01-74fe-4a80-bbab-7d66dd79df7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/div/input</value>
      <webElementGuid>8e70deeb-f194-4df3-8374-8ec6a3990990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_projcos' and @name = 'txt_lcinfo[projcos]']</value>
      <webElementGuid>26ac9a0d-1f57-4281-a4d5-faa296a9ad14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
