<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Goverment_project_description</name>
   <tag></tag>
   <elementGuidId>d7e39393-2c59-433e-bade-eadbd5155b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cell_site</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cell_site']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb8661ba-7e46-4b19-af7a-8cc5b7d71004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>386b291f-ab3c-4ee9-bd7c-dd4145de3694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell_site</value>
      <webElementGuid>2d6dd40a-d256-48d2-91bb-79301c99df03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>project_description</value>
      <webElementGuid>6581438a-ef84-4161-b2db-8244fb2ff39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>project_description</value>
      <webElementGuid>385d0d37-f7e2-400e-b314-f1d691405d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>cc44ede3-beb9-4702-a364-3b93390cf7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell_site&quot;)</value>
      <webElementGuid>80dd7c04-a9d8-49a0-956c-f6bcd4669fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>cbb79ab2-0228-4b8b-9dbf-3e0a5d39d269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cell_site']</value>
      <webElementGuid>dd87771c-1410-47ce-8d76-83108c07ba79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div/div[2]/div[5]/input</value>
      <webElementGuid>26465ee5-c698-412e-bc59-0c5f3eb319cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div[5]/input</value>
      <webElementGuid>5b5898ab-cc46-4176-b12c-e267734693e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cell_site' and @name = 'project_description']</value>
      <webElementGuid>597897c3-5394-4507-ac51-03fb09677db2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
