<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name of FirmCorpCo_txt_lcinfonfcc</name>
   <tag></tag>
   <elementGuidId>37c5a297-0bff-402d-82ce-206754863820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nfcc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nfcc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>292c3404-d2de-4c81-95e1-729faf9cb844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d4f9ebc-6272-40ff-80c6-6fc3864d2d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>8ba4eebf-6395-429c-ab52-ce293489489b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nfcc</value>
      <webElementGuid>4adb2c4c-6683-478c-86b1-262d8405f094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nfcc]</value>
      <webElementGuid>6eee100d-1b10-4682-9b86-08cf34b947c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>8ddc3c7c-9b4e-47c0-97bf-22b65d164e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>limitedtext</value>
      <webElementGuid>2b0682b0-21cf-43bb-9448-3e51db8f4abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nfcc&quot;)</value>
      <webElementGuid>2acd7b1f-076c-4d92-acc0-7ba7600b0e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>8f469938-b92f-45b5-82e0-4471a242665e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nfcc']</value>
      <webElementGuid>c4ca32b6-35d5-4bbd-b397-5934ca852085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[5]/div/div/input</value>
      <webElementGuid>c3f8a3e1-14d9-4f79-9566-6144038c2414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>3d889e34-1e37-43fe-bea2-e1ef32cc940e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nfcc' and @name = 'txt_lcinfo[nfcc]']</value>
      <webElementGuid>4cfae981-1792-4a30-89a9-506786248182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
