<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfonopgm_ln</name>
   <tag></tag>
   <elementGuidId>39f0da60-a84a-4ce2-bd9a-c378db7e709c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_nopgm_ln</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_nopgm_ln']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb0a7683-30e2-4f38-b309-092db812559a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d77ed8db-f4cd-46d8-81f0-6b00ef64108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>3fc46924-5701-4b03-9cd1-291b08462dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_nopgm_ln</value>
      <webElementGuid>8441b0b6-09ce-4d5f-aeeb-1f5516213cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[nopgm_ln]</value>
      <webElementGuid>7e84a10f-38bd-4555-9e72-fee860531527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\-\.][\u00F1\u00D1a-zA-Z\s\-\.']+</value>
      <webElementGuid>b8491abc-9c70-4445-a31c-6df11252036e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>personname</value>
      <webElementGuid>74b78d92-1f55-4404-ae52-c41629a97c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_nopgm_ln&quot;)</value>
      <webElementGuid>0c5bcc5c-d8ea-4611-9c20-010f3c9bec9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>d41d89fd-b5b8-4a21-9569-d4b98e42e4c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_nopgm_ln']</value>
      <webElementGuid>1e4fa19d-8375-4547-aaa1-44eefac75f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[2]/div/input</value>
      <webElementGuid>752a450e-f107-438f-86fd-711485871fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>feecd760-1582-49bc-a0e0-659a71aa225d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_nopgm_ln' and @name = 'txt_lcinfo[nopgm_ln]']</value>
      <webElementGuid>f7536fb5-5ba7-4be6-be5c-bae3591c1586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
