<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross Floor Area of Building (sqm)_tx_aa6ffc</name>
   <tag></tag>
   <elementGuidId>55300540-d294-413a-8c4b-2d09474363aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_gfab_sqm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_gfab_sqm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87c4888c-8a0c-4be8-9f06-c5b7ab231db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>564ff66c-5aa7-4050-823d-2f2b6868efad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>d8ec941e-ca87-4626-a258-50f88f683bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_gfab_sqm</value>
      <webElementGuid>a61de109-67e9-410a-91be-f99c8dec11f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[gfab_sqm]</value>
      <webElementGuid>4b491b6f-ad73-4445-91d4-79acd15a2bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>4ba9c0cb-3187-44f9-b9ec-ae111ff23408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>11bbad1f-a037-4ab7-9cf9-31e65a948ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_gfab_sqm&quot;)</value>
      <webElementGuid>099a725a-ad17-4fed-be84-69105e0fd154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>f39d5c74-df05-4fc1-b0c1-2d21bb63ac83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_gfab_sqm']</value>
      <webElementGuid>1b1c7b01-7f1c-4940-a426-1f1643aa9dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>eca8bcae-e4b2-4948-a302-78e0090579e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[3]/div/input</value>
      <webElementGuid>06045649-bef3-4cc4-aae2-b38530f0254c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_gfab_sqm' and @name = 'txt_lcinfo[gfab_sqm]']</value>
      <webElementGuid>f874a909-cfa6-4913-a06f-a7ce73b0c1f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
