<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfohblasubf_lpe</name>
   <tag></tag>
   <elementGuidId>ad3d00da-d682-44cf-a6a3-7649002f1723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_lhne_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_lhne_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdebc694-df52-4863-bea0-47d0af8efdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44ab4e0c-3fa3-412a-bf0a-37ec61979e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>0a77ba38-e4fa-4e0f-8d4d-3fe3846be097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_lhne_lpe</value>
      <webElementGuid>8565ff21-009e-40ab-acce-d0be7ad4715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[hblasubf_lpe]</value>
      <webElementGuid>51762f18-3322-438e-80bf-6cad3592b06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>bc86920c-f525-4375-bba0-2fbd837b1f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>addressfields</value>
      <webElementGuid>f3a19958-d868-4d7d-806f-43b6bfe86b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_lhne_lpe&quot;)</value>
      <webElementGuid>f3f4e337-eb5b-463b-b4b6-f6dd95972e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>f84ef4b5-6ca1-4980-9943-7141327cf044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_lhne_lpe']</value>
      <webElementGuid>e8cbe18d-6ef4-437d-8baa-0d68be9057cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div[2]/div/div/input</value>
      <webElementGuid>dd88521e-8d4a-49f0-a8e1-99bba8c271dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>6f6ddd7d-bec3-4f94-95ce-5387760ac8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_lhne_lpe' and @name = 'txt_lcinfo[hblasubf_lpe]']</value>
      <webElementGuid>46ed8a58-8b05-412d-a5be-7be18e1d631d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
