<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfophno_case</name>
   <tag></tag>
   <elementGuidId>70de8078-ec61-46c2-980e-55008b8c1de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_phno_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_phno_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90e0f035-63d6-411b-a2f9-e3c41a207843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99654a6c-cfa6-431d-8f5e-2070b50240ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>7430611f-d7a7-45bf-ae19-0f51974bba3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_phno_case_2</value>
      <webElementGuid>7ca4bc56-7b52-44a7-b2b0-d8283efd4d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[phno_case]</value>
      <webElementGuid>12c38bf8-826c-4135-85a5-ee542001f8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>9XX-XXX-XXXX</value>
      <webElementGuid>919f4827-4432-4b32-9325-5db8e7d6011e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[9][\d]{9}</value>
      <webElementGuid>76afae37-754a-4517-bfab-c9377661d011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>ad412dae-c78b-4093-9df5-72cda207e5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8e09575f-ea27-4a77-a512-aad76794ba15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_phno_case_2&quot;)</value>
      <webElementGuid>96c70cd5-eb08-491b-945e-e41a2354f6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>123e5b3e-934e-4e21-804d-e709550c1860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_phno_case_2']</value>
      <webElementGuid>9c39f28b-603c-4d80-b50c-b56b85a029a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>0091eb4d-0ed1-4e32-bd31-6b1f473b12b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>a131843e-3838-42ca-a4f6-98be199b1de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_phno_case_2' and @name = 'txt_lcinfo[phno_case]' and @placeholder = '9XX-XXX-XXXX']</value>
      <webElementGuid>5fa154e0-e991-410d-a135-076fdf3025d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
