<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfoemail_case</name>
   <tag></tag>
   <elementGuidId>c4f86d07-fd2e-42e1-9688-7fff37684c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_email_case_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_email_case_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53db3c2c-b23f-414e-87cb-6a017ea9f7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd94a995-43f8-4636-88f4-c2e4a46db3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>191a7361-897b-4f6b-b8ef-786436bfad76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_email_case_2</value>
      <webElementGuid>d5183ff7-e84d-4982-b573-c1640d774f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[email_case]</value>
      <webElementGuid>330e8293-42d0-4f72-ad8a-d7abb538facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9\-\._%+]+@([a-zA-Z0-9\-]{2,}\.)+[a-zA-Z0-9\-]{2,4}</value>
      <webElementGuid>5c6a66ff-bab8-409d-ab05-211d07467ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1024288d-c372-46e1-a376-e5263c691dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_email_case_2&quot;)</value>
      <webElementGuid>3e44ce22-ea2a-4b3a-b323-0161f602ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>226d9c1c-ffe7-46ca-a971-85e07d670791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_email_case_2']</value>
      <webElementGuid>ad7ec570-73aa-446e-b9af-783fc7287c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>e8495cc7-0de6-45c1-b6b1-153f7a300fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>3440b2b1-0ad1-47e4-be45-f73348a77c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_email_case_2' and @name = 'txt_lcinfo[email_case]']</value>
      <webElementGuid>8959da1a-410e-44ec-8e75-dca1981ab302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
