<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfotctno</name>
   <tag></tag>
   <elementGuidId>32571ed3-e6e1-43fe-a2d6-f192c3159d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_tctno_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_tctno_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2f53862-3fce-4a3f-b5a3-0702f5f3c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f95d95cd-50cc-4704-80ab-fa252331269f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bce6d347-ca1e-44fd-8ea8-57bf873a38af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-class</name>
      <type>Main</type>
      <value>text_tctno</value>
      <webElementGuid>63a11990-5916-4e41-8115-dfa8dd44ae83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_tctno_1</value>
      <webElementGuid>477b50bf-3aa3-44ba-bc97-80e9fc223afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[tctno]</value>
      <webElementGuid>40adceaf-9bff-45f2-b0df-52c6c2b38492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{1,}</value>
      <webElementGuid>4c534300-c507-4c4c-acd8-e65b1fdaaa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>801c5c3f-0cdf-40c7-888d-169e6c81ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_tctno_1&quot;)</value>
      <webElementGuid>a05c5cbc-099c-4df9-a98f-0d5de762601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>85638e5e-4712-4bdc-b30e-2d8b3f731007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_tctno_1']</value>
      <webElementGuid>76cdf0e5-5866-4782-b613-0436caad5aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tct_container']/div/div/div/input</value>
      <webElementGuid>cf81d68b-3bb5-476d-8060-b52246bbda27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>66e2a4d6-10c6-4508-92f9-081ddfab651e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_tctno_1' and @name = 'txt_lcinfo[tctno]']</value>
      <webElementGuid>e1f0c20c-31cb-47cd-9cba-ce76f618a02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
