<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfotfab_sqm</name>
   <tag></tag>
   <elementGuidId>75c42ffe-12c8-47be-aa45-b1c39425448e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_tfab_sqm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_tfab_sqm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dffbbcb9-ec61-4152-8fa8-3494fbfd3ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22d8e7ea-6974-4356-860c-39ec6c7af479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo is-valid</value>
      <webElementGuid>d6c9bcb6-7c63-4b5f-a959-31bae2b3d163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_tfab_sqm</value>
      <webElementGuid>02ab3a52-ca9a-46c0-a537-5f6808e00267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[tfab_sqm]</value>
      <webElementGuid>5bf50df5-fd33-49ea-9b9c-a88d47dec566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d,]{1,}[.]{0,1}[\d]{0,}</value>
      <webElementGuid>f5360864-de86-4016-ba2c-db99ef92c97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>float</value>
      <webElementGuid>b3257fc4-1561-484e-8eb0-2d2ebb9f0119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_tfab_sqm&quot;)</value>
      <webElementGuid>63ecdabc-ce46-4287-b8bf-ca20ee101995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>44ad017c-3d1e-4091-84a5-cb3d15905265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_tfab_sqm']</value>
      <webElementGuid>e1eaafbe-4f92-48ee-bb3b-9f0c375be0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[9]/div[2]/div[2]/div/input</value>
      <webElementGuid>5ce8c776-5b8d-4e5e-becb-fad1d564b783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/input</value>
      <webElementGuid>3873324d-6f70-4774-88a6-46e41916f430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_tfab_sqm' and @name = 'txt_lcinfo[tfab_sqm]']</value>
      <webElementGuid>0fd27477-eaf3-46ce-aa35-b63e0310a995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
