<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_txt_lcinfozipc_lpe</name>
   <tag></tag>
   <elementGuidId>f3de5a1d-b440-4851-aba4-047a1d34614e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_zipc_lpe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_zipc_lpe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfbfb396-899a-4a88-b691-46ebc609a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3eb8d5c-fbe9-4e43-bd04-8c47b9ddaa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>bed9ec33-2a49-4d92-b921-156b674b8a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_zipc_lpe</value>
      <webElementGuid>855aa7ff-2b78-48b6-a6cc-103773f773a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[zipc_lpe]</value>
      <webElementGuid>0ce1eef9-7271-4b97-b546-f48dc21037c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[\d]{4}</value>
      <webElementGuid>ac256807-6681-41b8-a818-d637ae04b823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>a36790d0-22fb-44e3-9857-279221add9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXX</value>
      <webElementGuid>682b902a-6eaf-4a0d-a0f9-338db9b847d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>523dfefa-bb14-425f-8c95-72022f9c9b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_zipc_lpe&quot;)</value>
      <webElementGuid>c5da1c3c-7c83-43d8-ba5f-22cf4b155b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>8da2f1be-6c79-4f42-8ce3-4191e63f60d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_zipc_lpe']</value>
      <webElementGuid>391cf9c6-54ae-407f-a574-f68aa8dc09cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>f07fdd21-f94a-4ca4-81ab-28d4a25c098c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div[2]/div/input</value>
      <webElementGuid>faf5ee22-6421-4804-a4b5-32217a622509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_zipc_lpe' and @name = 'txt_lcinfo[zipc_lpe]' and @placeholder = 'XXXX']</value>
      <webElementGuid>6792ed0f-dca9-4bf7-a721-1cc5eb943dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
