<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_lcinfohblasubf_ha_1</name>
   <tag></tag>
   <elementGuidId>7672e394-c609-458d-b785-c06617322836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_stadvie_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text_stadvie_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcdbbed6-7ffd-47ca-ad1b-d75c24b22c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72ccfad4-6ac3-440d-afb3-fd785a2d2eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt_lcinfo</value>
      <webElementGuid>d3ab59b7-c8a5-4645-ab99-c8b9acbe6cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_stadvie_ha</value>
      <webElementGuid>d7f9bd3d-ce57-4a5a-a240-756df09d7378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[hblasubf_ha]</value>
      <webElementGuid>052f0684-1b41-49bd-8432-81abccc42bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^\s\.\,][\u00F1\u00D1a-zA-Z0-9\s\-\#\,\.\(\)\+\/:!@'\?]+</value>
      <webElementGuid>afc0262c-53e6-45fc-8ce5-a874ee289144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-type</name>
      <type>Main</type>
      <value>addressfields</value>
      <webElementGuid>6e82a6db-5ea7-4a5d-806d-5272976bd91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_stadvie_ha&quot;)</value>
      <webElementGuid>dd610aac-5120-4abb-a321-acfcf214c430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>15d38b63-57da-48d0-9441-d11fc23a0b8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text_stadvie_ha']</value>
      <webElementGuid>d14a3945-1fee-41e3-ab93-baefc9df3fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div[2]/div[3]/div/input</value>
      <webElementGuid>e8f539c5-1eff-4f0e-9099-87d8514cf68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[3]/div/input</value>
      <webElementGuid>8b218241-5e27-438b-a5c1-fdebd3385f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text_stadvie_ha' and @name = 'txt_lcinfo[hblasubf_ha]']</value>
      <webElementGuid>17218b26-6f64-48c1-b1cd-02fb78ddced4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
