<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invalid field. Please enter proper te_3469a4</name>
   <tag></tag>
   <elementGuidId>df393db1-a117-4243-bd5b-e667eded02f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox_middle_name_nopgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox_middle_name_nopgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b884587-0d88-456b-9a70-13619eb7aa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>08b58561-16ed-4b35-9c51-f1ee312fc866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input txt_lcinfo</value>
      <webElementGuid>ba3c482b-0925-41ae-b1bf-c4ff562b7952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox_middle_name_nopgm</value>
      <webElementGuid>628c415d-5ae4-4b40-b81c-c07b55e13c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[no_middle_name]</value>
      <webElementGuid>91076364-879c-456e-bb54-5c45f448c220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_middle_name_nopgm&quot;)</value>
      <webElementGuid>402b7a4f-ff8f-48f6-a2c7-22dd8973507a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>0d43db90-d489-4fae-a9b6-517f1a398f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox_middle_name_nopgm']</value>
      <webElementGuid>0473ce00-24bc-4ca5-b5c6-b826ff7207ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>ec341ca6-84ec-48a9-88b2-0802eaa184b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>7aca67cf-cf32-4541-ae52-d85629d05097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox_middle_name_nopgm' and @name = 'txt_lcinfo[no_middle_name]']</value>
      <webElementGuid>cefaa99c-bb8a-468c-aba1-1af385a3014e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
