<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select City -City of Roxas (Capita_e76b7b</name>
   <tag></tag>
   <elementGuidId>e414a312-96d9-4be5-97cd-8b299ce466b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_city_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_city_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7bd545cf-fa25-4645-91ba-f8e77747feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[city]</value>
      <webElementGuid>5d2e7a54-3fde-44e9-b118-da0bd3470f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>e572d25a-cc78-461e-bda9-b101b031cdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control custom-select psgc_fields</value>
      <webElementGuid>67158473-9099-4880-8fc1-15b3ca1fdfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>0dbc0c01-81e1-49d0-941a-cd844a0a32b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brgyid</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>040cf682-c549-4d8d-be43-16611e57fe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_munci_change(this)</value>
      <webElementGuid>0f3505fe-fcd2-449d-86ec-9c850d16042d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select City -City of Roxas (Capital)CuarteroDaoDumalagDumaraoIvisanJamindanMa-AyonMambusaoPanayPanitanPilarPontevedraPresident RoxasSapi-AnSigmaTapaz</value>
      <webElementGuid>1d627612-4bd7-4e8e-a0f0-9b0af15ef101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_city_ha&quot;)</value>
      <webElementGuid>173f4899-3a1b-4746-8c1e-e572e2be25e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>dffbe9aa-eed1-4283-949c-07ad947bcf6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_city_ha']</value>
      <webElementGuid>fc7f5d98-bc4b-43f8-9836-748231b35e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[3]/div/select</value>
      <webElementGuid>47a79e80-7737-4506-b21b-51136e77e593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[27]/following::select[1]</value>
      <webElementGuid>2b0279ba-b3f2-4f80-91f4-596dcbc7eb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a City.'])[1]/preceding::select[1]</value>
      <webElementGuid>b95d1f0a-63db-405c-b8fd-1308e8e49188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>42d87f3b-cb91-452a-a9b7-85fe8fd403e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[city]' and @id = 'select_city_ha' and (text() = '- Select City -City of Roxas (Capital)CuarteroDaoDumalagDumaraoIvisanJamindanMa-AyonMambusaoPanayPanitanPilarPontevedraPresident RoxasSapi-AnSigmaTapaz' or . = '- Select City -City of Roxas (Capital)CuarteroDaoDumalagDumaraoIvisanJamindanMa-AyonMambusaoPanayPanitanPilarPontevedraPresident RoxasSapi-AnSigmaTapaz')]</value>
      <webElementGuid>d36a3b15-7363-4e61-b9e8-3bded48b0f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
