<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Province -AklanAntiqueCapiz_59b881</name>
   <tag></tag>
   <elementGuidId>c7be1907-fab1-4654-9c1d-a11e90432dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_province_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_province_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>335bc3b2-83d7-43f0-ae8f-16a94ace8b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[province]</value>
      <webElementGuid>ee1cba4d-977e-4999-a642-b0d6ea5b7fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_province_ha</value>
      <webElementGuid>94b88ae3-3180-4adc-a8a7-4c9b97e4abce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control psgc_province custom-select psgc_fields</value>
      <webElementGuid>9c3abd12-991d-4114-a816-b20666207bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cityid</name>
      <type>Main</type>
      <value>select_city_ha</value>
      <webElementGuid>97f5bf00-0c2c-42b2-aaad-e160863053be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>892e2e31-5b44-488c-a91e-64fc1014481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_province_change(this)</value>
      <webElementGuid>e7f30ad3-48f7-4345-ab2e-8d5f6265ce6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Province -AklanAntiqueCapizGuimarasIloiloNegros Occidental</value>
      <webElementGuid>e79dc5cd-e1b6-42e0-ab80-be857bef8844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_province_ha&quot;)</value>
      <webElementGuid>620c1f6a-4994-4023-a686-aad1d3befbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>6d9ee12f-721e-4680-b578-6189e8b40941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_province_ha']</value>
      <webElementGuid>ee20ac48-8eff-4ecd-976b-ee3e5a3c52d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[2]/div/select</value>
      <webElementGuid>b6f7d7eb-de4b-4c84-b79a-eb990f859e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[26]/following::select[1]</value>
      <webElementGuid>009d49e9-0098-4cf8-a892-86a9bd5a3dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Province.'])[1]/preceding::select[1]</value>
      <webElementGuid>56bb9bf9-8f35-486b-8e9a-8706f44bb2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>61325efb-35fe-47bf-97f4-490b216f9484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[province]' and @id = 'select_province_ha' and (text() = '- Select Province -AklanAntiqueCapizGuimarasIloiloNegros Occidental' or . = '- Select Province -AklanAntiqueCapizGuimarasIloiloNegros Occidental')]</value>
      <webElementGuid>1e679dd5-d6e6-45fa-8875-0aa05fa2cd67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
