<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Barangay -AcboAmagaBalucuan_e59043</name>
   <tag></tag>
   <elementGuidId>b01fd747-c88b-4054-9e2b-ee34e239e526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select_barangay_ha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_barangay_ha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f7de42e-3f5b-4d7d-b60f-e6ed2c9c0633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_lcinfo[barangay]</value>
      <webElementGuid>ba1ba298-8f52-465f-8ea1-c537f5ef9f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_barangay_ha</value>
      <webElementGuid>a242993f-515d-41e5-b637-61a1efbc32dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bgy_sel custom-select psgc_fields</value>
      <webElementGuid>f92faaf0-049b-463d-bb99-ee9d4e0e99a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zip</name>
      <type>Main</type>
      <value>text_zipc_ha</value>
      <webElementGuid>b6f12062-ca18-4b91-bdfd-260a835cb40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>psgc_brgy_change(this)</value>
      <webElementGuid>5eaa1fd5-ab18-46a9-a87d-5c2e460c384f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Barangay -AcboAmagaBalucuanBangonbangonCapuyhanCogonDayhagonGuintasMalapad CogonMangosoMansaculMatangcongMatinabusMianayOyongPagbunitanParianPinamalaticanPoblacion NortePoblacion SurTawog</value>
      <webElementGuid>b398295c-ce63-4c84-bf11-f72850343200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_barangay_ha&quot;)</value>
      <webElementGuid>ee9b4b1f-566e-44e0-8e7b-ccb75e190add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Application Form/Page_Mandaluyong E-Services/iframepage-content-wrapper</value>
      <webElementGuid>78e628f8-1c92-45e2-b656-0e2f5442f01f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_barangay_ha']</value>
      <webElementGuid>b3eecd49-fe9c-4ecb-b233-77a5b661b909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information_section']/div[6]/div/div[4]/div/select</value>
      <webElementGuid>b503566a-4ae2-46bc-81d3-819a133f5221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[28]/following::select[1]</value>
      <webElementGuid>28d3e89e-a28c-483e-b431-24ad5d4c683f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a Barangay.'])[1]/preceding::select[1]</value>
      <webElementGuid>16265c60-6dd3-4fc0-9d07-ec9330a926e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[4]/div/select</value>
      <webElementGuid>c90c8b83-9813-46e4-a7f3-7c1a04855ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_lcinfo[barangay]' and @id = 'select_barangay_ha' and (text() = '- Select Barangay -AcboAmagaBalucuanBangonbangonCapuyhanCogonDayhagonGuintasMalapad CogonMangosoMansaculMatangcongMatinabusMianayOyongPagbunitanParianPinamalaticanPoblacion NortePoblacion SurTawog' or . = '- Select Barangay -AcboAmagaBalucuanBangonbangonCapuyhanCogonDayhagonGuintasMalapad CogonMangosoMansaculMatangcongMatinabusMianayOyongPagbunitanParianPinamalaticanPoblacion NortePoblacion SurTawog')]</value>
      <webElementGuid>1a90a534-1c5f-46b0-bbd3-8f29be408b2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
