<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframepage-content-wrapper</name>
   <tag></tag>
   <elementGuidId>8380d4f0-b01d-486c-a9bc-923086bff93d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>aa718d5e-9824-4c92-b889-83f5ce970ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>bc9e064a-b633-4649-a93b-cf0081e7310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://adminmandazauqa.unifysyscontrol.com/Homepage/index?UserID=24&amp;UserTypeID=1&amp;as=Mjg0fQJJRD0yNHxLZXk9U2FuZG1hbkN5cGhlcnxGTmFtZT1aQVV8TE5hbWU9VXBsb2FkZXJ8Q29udGFjdD0wOTU0IDg1NSA2e1VzZX</value>
      <webElementGuid>a5ac2034-c5ac-4887-84c7-9c2e40139342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>ee02fc4b-d26e-41e2-b293-516df8c401b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>aa275d65-a0c2-400b-a4f1-453479247d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>d5b79296-465b-499c-8214-890f72db6c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8911bc1e-2c46-4ae6-a318-afb6d448edfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://adminmandazauqa.unifysyscontrol.com/Homepage/index?UserID=24&amp;UserTypeID=1&amp;as=Mjg0fQJJRD0yNHxLZXk9U2FuZG1hbkN5cGhlcnxGTmFtZT1aQVV8TE5hbWU9VXBsb2FkZXJ8Q29udGFjdD0wOTU0IDg1NSA2e1VzZX']</value>
      <webElementGuid>eb171293-735a-4a94-b0ae-55b69a401de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
