<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>7bcc77d6-9461-43ee-b731-ece7ba353c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07ea0e95-89f6-4caf-9c40-379844782b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>375398bb-7efc-422a-81b0-a8c9f048cc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb305284-095b-40a0-94a4-f0114d695fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_password</value>
      <webElementGuid>c0ced496-b8d4-45ae-8c59-5c0f3d8ccc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter password</value>
      <webElementGuid>b1748f9c-7802-41b1-a6cc-b8b6ab857022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>58edd488-a1d6-4be0-8f1d-675861ece2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>a9c124a3-bbdf-41b4-af1c-d9eb1af3b8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_password&quot;)</value>
      <webElementGuid>1788ddcd-dcba-4142-942c-95a297d2f531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_password']</value>
      <webElementGuid>80d67359-cd49-42ea-bb18-f16702fbe37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_div']/div[2]/div/input</value>
      <webElementGuid>c8d24301-005d-428e-ab56-65c5862faf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>b68d20b2-6eb1-4ede-9611-68ec7e9cdc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input_password' and @placeholder = 'Enter password' and @name = 'password']</value>
      <webElementGuid>73e1a742-93e2-423c-b881-d83050028387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
