<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Capture object_page-content-wrapper</name>
   <tag></tag>
   <elementGuidId>2917105f-84b5-4b46-bbe7-c26fd18ec2f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='page-content-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1fdb1390-2bd4-4878-a9d4-e98ca6cb3121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-content-wrapper</value>
      <webElementGuid>4c1f59cb-839f-45dd-8b75-031b744baa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX</value>
      <webElementGuid>279f597a-5546-4a63-b049-894186fa3f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>adjustIframeHeight(this)</value>
      <webElementGuid>76718f74-1bc0-410b-9eac-56e664fbc024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)</value>
      <webElementGuid>bc15b834-57d5-4a29-8b1b-bfa690a6df36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='page-content-wrapper']</value>
      <webElementGuid>7a2b9c8b-5504-44b4-a5df-7a7ec908fb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>31c12943-f8a3-4490-afac-40a1dcb8da1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'page-content-wrapper' and @src = 'https://mandazauqa.unifysyscontrol.com/Homepage/index?UserID=3&amp;UserTypeID=1&amp;as=NTQ2fQJJRD0zfEtleT1TYW5kbWFuQ3lwaGVyfEZOYW1lPUd3ZW58TE5hbWU9QXB1bGl8Q29udGFjdD0wOTIzIDU0NSA2e1VzZX']</value>
      <webElementGuid>836c6475-a6a1-4e77-a7a2-e12a5385e4a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
